### ISSUE TITLE
Ceph FSAL root_squash does not work as expected

### ISSUE THREAD

**Issue by kwaegema** [nfs-ganesha/nfs-ganesha#102]
Testing with 2.4-o-dev20:
I did set root squash on in the ganesha.conf, but as root I can do metadata operations through the nfs mounts like creating direcories and running touch. Writing actual data data or changing permissions does not work, so that is ok. Also these created files/dirs also show up as root in the cephfs.

**Comment by ffilz** [comment]
What did you do for your anonymous uid/gid? The default -2?

A while back I identified a problem with the libcephfs interface which allows the caller to pass the credentials to use for the operation. Unfortunately, it's a signed value, and it utilizes negative values for the "default" of using the process credentials instead. Which means the typical -2 nfsnobody id (which considering uid_t is a uint64_t really is a really big positive number, but when passed to libcephfs, it becomes negative again since the libcephfs params are int64_t) tells libcephfs to use process credentials, which of course are root.

The current suggested workaround is to use a non-negative value for nfsnobody/anonuid, perhaps INT64_MAX or something like that.

**Comment by kwaegema** [comment]
Thanks! We will try with the workaround for now, I created an issue for ceph http://tracker.ceph.com/issues/16367

**Comment by kwaegema** [comment]
looks like it is resolved in ceph: http://tracker.ceph.com/issues/16367

**Comment by ffilz** [comment]
Actually, I'm going to keep this open, the cephfs API is changing which will necessitate Ganesha changes in order to work with it.

**Comment by ffilz** [comment]
I just did a quick verification, this should be good now.
