### ISSUE TITLE
Inquiry about state_hdl

### ISSUE THREAD

**Issue by Bingo0203** [nfs-ganesha/nfs-ganesha#1039]
Hello, gentleman:
    For nfsv4, can "obj->state_hdl" only be obtained or created through the mdcache layer?
    Is there a way to directly obtain the state_hdl from the underlying layer?

struct fsal_obj_handle {
   struct state_hdl *state_hdl;
}

Thanks

**Comment by ffilz** [comment]
It really is purely a feature of mdcache. What is your need for it, maybe I can suggest how to get to it.

**Comment by Bingo0203** [comment]
Thanks, what I would like to know is as follows:
What is the specific function of "state_hdl"? (state management, metadata manipulation, etc.)
Can "state_hdl" be gotten from the bottom?
Is it feasible to remove "state_hdl" directly?

**Comment by ffilz** [comment]
Ok, so state_hdl was added to contain information relevant to state (open, lock, delegation, layout) for a file, or junction information for inodes that are junctions in a way that did not force that information into mdcache. The structure can not be removed as it serves a critical purpose for those things. There is no need to access it from the bottom (by this I assume you mean the underlying FSAL such as FSAL_CEPH) since it is all protocol layer information.

At the time it was conceived, it was thought we might be able to have FSALs without FSAL_MDCACHE on top of them so it needed to be able to be separate from mcdcache. But even with the fact that it turns out FSAL_MDCACHE is always necessary and it MUST be the top FSAL in a stack, the information in the state_hdl doesn't belong to mdcache so is defined separately (though technically the junction information is export related...).

**Comment by Bingo0203** [comment]
Thanks, I'd like to know more about the details of the functionality of the state_hdl piece, and if you can provide some of the corresponding community commits for this so I can deepen my understanding of this piece!

**Comment by ffilz** [comment]
Not much details. Basically it came about when Cache_Inode was being converted to FSAL_MDCACHE and there was expectation that we could operate without FSAL_MDCACHE in which case there needed to be a separate place than the mdcache inode to keep this information (it used to be in the cache_inode inode). Now the truth is that we can't operate without FSAL_MDCACHE because it also served as the handle cache. Still, it's helpful to have this information in a separate structure than the mdcache inode so it is available to the protocol layer (the mdcache inode is an internal structure based on a fsal_obj_handle so is opaque outside the specific FSAL).

**Comment by ffilz** [comment]
Can we close this?

**Comment by ffilz** [comment]
Closing, responded over 30 ago
