### ISSUE TITLE
FSAL CEPH: functionality for non-default users

### ISSUE THREAD

**Issue by kwaegema** [nfs-ganesha/nfs-ganesha#104]
Right now, the ceph fsal only could be used with the default ceph.client.admin.keyring (so default 'admin' user).
It would be nice to be able to use a specific user for this (which should be possible with libcephfs)
Could this be an option? Thanks!

**Comment by ajarr** [comment]
@kwaegema FSAL CEPH  options `User_Id`, and its `Secret_Access_Key` have been introduced since
https://github.com/nfs-ganesha/nfs-ganesha/commits/d3c0bfa2ce9c6c63942a429943cd3b73a4ca8a25
to allow non-default cephx userid to talk to CephFS backend. Look at https://github.com/nfs-ganesha/nfs-ganesha/blob/next/src/config_samples/config.txt for more details on the FSAL_CEPH options

**Comment by ajarr** [comment]
@ffilz @jtlayton can this issue be closed?

**Comment by jtlayton** [comment]
Yes, I think so with the current code in "next" branch.

**Comment by ffilz** [comment]
Can we close this issue? I will close it next week if there is no response otherwise.

**Comment by kwaegema** [comment]
Ah thanks, this is what we needed!
