### ISSUE TITLE
Can we identify clients with the same hostname with NFSv4.1 and 4.2?

### ISSUE THREAD

**Issue by bear-Zhao178** [nfs-ganesha/nfs-ganesha#1045]
We have encountered some issues with ganesha when dealing with NFSv4.1 and 4.2, as it cannot differentiate between clients with the same name. Is there a way for us to add the client IP to the co_ownerid and use it to distinguish between clients with the same name?

Currently, the client_record is retrieved based on the co_ownerid as the key.

**Comment by bear-Zhao178** [comment]
our version is v3.2.

**Comment by bear-Zhao178** [comment]
Can we refer to the method in NFSv4.0 to distinguish clients with the same hostname?

**Comment by ffilz** [comment]
The 4.0 client.id or 4.x co_ownerid strings MUST be unique between clients. We can not append the IP address to that because of multi-homed clients. There IS a way to provide a unique ID for each client instead of using hostname documented here for the Linux client:

https://www.kernel.org/doc/html/v5.8/admin-guide/nfs/nfs-client.html

**Comment by bear-Zhao178** [comment]
OK, thank you a lot, please close this issue.
