### ISSUE TITLE
Enforce unique Client ID generation

### ISSUE THREAD

**Issue by zhitaoli-6** [nfs-ganesha/nfs-ganesha#1190]
Dear community, 

In our system, the clientid4 plays a pivotal role in managing state and recovery. It's essential that clientid4 values are unique both within a nfs-ganesha node and across multiple nodes.

Currently, the clientid4 consists of a 4-byte server epoch and a 4-byte increasing unsigned integer. However, this approach has two potential issues:
- Time-Based Collisions: Multiple nodes might start with the same second-level timestamp.
- Integer Rollover: The increasing unsigned integer could eventually reach its maximum value and roll over to zero.

The enforcement may look as following:
- Node ID: Include the node's unique identifier within the clientid4. This can be achieved by allocating a portion of the increasing unsigned integer to represent the node ID. For instance, in a 64-bit clientid4, we could use 32 bits for the server epoch, 8 bits for the node ID, and 24 bits for the increasing unsigned integer.
- Prevent Integer Rollover:  Simply coredump nfs-ganesha when the increasing unsigned integer from roll over to zero.

**Comment by ffilz** [comment]
There are a couple options already existing to help this situation:

-E parameter on command line, replaces nfs_ServerEpoch with a value provided on the command line.

NFS_CORE_PARAM - Unique_Server_Id replaces nfs_ServerEpoch with a value provided in the config file.

With either of these options, the service can generate a server epoch that is a combination of a start instance and a node ID. Using up to 16 bits for node id is more than enough node ids, then have a counter that increments each time ganesha starts on a particular node should easily give unique server ids for a cluster. That leaves 32 bits in clientid4 for a counter of clientids for that server instance and 32 bits in stateid.other for stateids for that clientid instance. If fewer nodeids are used, of course, fewer bits can be used for nodeid and more for instance. With 8 bits nodeid and 24 bits for a start time, that gives 194 days before the start time wraps, or 388 if you divide the time_t by 2. There are probably other ways of generating an instance id.

These options can be used without any Ganesha code change.

As to rollover of the 32 bit counters... That seems incredibly unlikely to be an issue, but sure, we could LogFatal on wraparound. Optionally, we can just use the next count value if a collision with an active clientid or state is detected. With the courteous server stuff, we don't instantly flush expired states so that should minimize chance for a client to come in with an expired clientid or stateid that has already been re-used.

**Comment by zhitaoli-6** [comment]
Thanks for you reply. It helps a lot.
