### ISSUE TITLE
Known or suspected memory leaks in 5.9?

### ISSUE THREAD

**Issue by james-munson** [nfs-ganesha/nfs-ganesha#1207]
Hi.  The question comes up because in some testing of its use in Longhorn, (https://longhorn.io), it appears that there may be higher memory consumption in 5.9 than in 6.2.

Looking through the list of open issues, there doesn't seem to be anything major.  But there have been three commits to 6.2 that look like they address issues present in 5.9 based on the code they touch:

* fd7dc2254 STATE: fix a state_t refcount leak and a couple minor cleanups
https://github.com/nfs-ganesha/nfs-ganesha/commit/fd7dc22542d8f6686a7d5859539c510bde148874
* f1013e19c Fix so_refcount leak
https://github.com/nfs-ganesha/nfs-ganesha/commit/f1013e19cddc354452b72e6033acd3382de9cdf4
* 12a9abd7f nfs_rpc_callback: Assert in case no completion function is set as we will have a cb resource leak
https://github.com/nfs-ganesha/nfs-ganesha/commit/12a9abd7ff3d74083570d11acec194ac0a70c4f5

Is that correct?  Are there any others we should be looking at?
Thanks!

**Comment by ffilz** [comment]
It really is strongly recommended to move from 5.9 to 6.3. Since the community only commits to supporting a single stable release, and the number of fixes continuing to come in has been significant, we made a decision NOT to make the effort of identifying patches for a final 5.10 release.

While that is a good list of memory leak fixes, there are also other significant fixes missing from 5.9.

**Comment by james-munson** [comment]
Got it, thanks.
