### ISSUE TITLE
Steady high CPU usage with FSAL Gluster

### ISSUE THREAD

**Issue by freezoo2** [nfs-ganesha/nfs-ganesha#124]
Hi,

I'm using Ganesha NFS in a LXC container and using Gluster FSAL as backend.  

When I define a single export, the CPU usage is 10% constantly on core i5  (without or without client mounting and using the server).  

When I define  8 export, the CPU usage is constantly at 45% for the Ganesha process.

I'm using Ubuntu 16.04 LXC container and Gluster 3.8.X

Is this CPU usage considered normal when the NFS server is sitting idle, not processing traffic?  If not, what might be causing this?

Thanks!

**Comment by dang** [comment]
No, this is abnormal.  I do not see CPU usage when no clients are active.  Maybe ask on the mailing list where there are Gluster people who can help you?

**Comment by soumyakoduri** [comment]
I guess that CPU usage is because of the upcall thread spawned for each of the export. This thread  keeps polling for any cache-invalidation requests from Gluster/gfapi. We tried to make this thread spawn optional (as it is needed only in HA setup) by checking the existing option "clustered" but there is some cleanup/fix needed in that area.

**Comment by ffilz** [comment]
Can this issue be closed? I will close it next week if there is no response otherwise.

**Comment by ryno83** [comment]
Hi,
I'm experiencing the same problem. No clients connected and ganesha.nfsd is around 15% CPU usage on each node. I'm using ganesha 2.5.0 with gluster 3.10.3 on Debian 8 Jessie
