### ISSUE TITLE
nfs over rgw - new bucket not show up unless restart Ganesha

### ISSUE THREAD

**Issue by TaoCHEN92** [nfs-ganesha/nfs-ganesha#137]
Hi all,
I'm using nfs-ganesha v2.4 to build a nfs over rgw with Ceph v11.0.2. I tried to create a new bucket in ceph cluster with s3cmd and the new bucket had been successfully created. However, I couldn't see the new bucket in the mount point unless I restart Ganesha. 

Is this some kind of caching bug?  Thanks a lot for your attention!

**Comment by dang** [comment]
As it currently stands, this is expected behavior.

Ganesha has a facility for the FSAL to notify it that a directory cache needs to be invalidated, called "UP calls".  RGW does not yet implement this.  This means that, once a directory has been cached by Ganesha, it will never be invalidated by changes to the cluster from outside Ganesha, such as s3cmd.  Work is underway to fix this, but it's not yet in.

**Comment by TaoCHEN92** [comment]
OK, thanks a lot for your reply!

**Comment by ffilz** [comment]
Can this issue be closed? I will close it next week if there is no response otherwise.
