### ISSUE TITLE
FSAL_RGW: rmdir succeed on non-empty directories with corrupted-like results

### ISSUE THREAD

**Issue by guihecheng** [nfs-ganesha/nfs-ganesha#153]
I found that 'rmdir' succeed on non-empty directories:
1. cd /mnt/rgw
2. mkdir dir1
3. touch dir1/file1
4. rmdir dir1    <-- return 0
but we could still found dir1 under `pwd`.

After digging into the rgw_file codes, I found that the directory empty check is not done at all.
Actually, I do think that this is a intended one just like that renaming a dir is not permitted for not scalable reason.
But If I do an extra rmdir on dir1, then dir1 get corrupted like stats when I do an ls.
something like:
??????????? ? ??? ???? ? ??  ???? dir1
I consider it to be not so nice.

So, any ideas to solve this one? perhaps add empty checks in rmdir operations with extra lookups(seems expensive)?

cc @mattbenjamin

**Comment by mattbenjamin** [comment]
@guihecheng hi!  you're right, this was omitted to avoid an expensive check, but going forward, we need to do better.  In particular, because I'm unsure why the ??? attrs are showing here, there definitely is an underlying problem with stored attrs, since demoting from a materialized dir node which might have explicit attrs saved to a common-prefix dir node is possible, and loses information.  I am in the process of doing a set of changes that deal with directory listing, which are combined with new ganesha apis for partial caching and safe updated of cached dirents;  this work cleans up and firms up what is known about directories that have been enumerated;  it will be easy to have a 'fast' check for positive children;  if the positive children check fails, though, I think we'll need a more expensive negative check that maybe uses enumeration to prove safety.  what do you think?

**Comment by mattbenjamin** [comment]
@guihecheng I think, after discussion w/Frank Filz, that we basically can't do the "fast check" I was proposing unless we have consistent caching.  

Created http://tracker.ceph.com/issues/19270/ to track this issue, and have wip patch to do the slow check.

**Comment by guihecheng** [comment]
@mattbenjamin I think enumeration is the only choise for now, thanks.
