### ISSUE TITLE
nfs-ganesha-config service not working on Debian

### ISSUE THREAD

**Issue by christmart** [nfs-ganesha/nfs-ganesha#161]
see bugs.debian.org/859955

systemd service file nfs-ganesha-config.service wants to exec /usr/libexec/ganesha/nfs-ganesha-config.sh but this file does not get installed. 

Also /usr/libexec/ganesha is be the wrong place. /usr/lib/ganesha/ is better.

src/scripts/nfs-ganesha-config.sh has to be changed to read from /etc/default/ganesha instead of /etc/sysconfig/nagesha.

Im am not shure if /run/sysconfig/ganesha has the correct path. I did not find a reference in Debian.

Christoph

**Comment by dang** [comment]
We don't have any debian packaging here, the Debian maintainers asked us to remove it.  You'll have to take it up with whoever made the packages you installed.

**Comment by kalebskeithley** [comment]
The nfs-ganesha Debian packaging bits are in the
  https://github.com/nfs-ganesha/nfs-ganesha-debian repo.
There's a separate issue tracker for that.

And there's already an issue open at https://github.com/nfs-ganesha/nfs-ganesha-debian/issues/1 for the nfs-ganesha-config.service problem.

Feel free to open another issue for the /usr/libexec problem so that it does not get forgotten.

We could definitely use some Debian packaging expertise.

**Comment by kalebskeithley** [comment]
fixed in 2.5.0-3 packages on download.gluster.org and the Launchpad PPA
