### ISSUE TITLE
(c)make install things like nfs-ganesha-config.sh

### ISSUE THREAD

**Issue by kalebskeithley** [nfs-ganesha/nfs-ganesha#188]
See, e.g., https://github.com/nfs-ganesha/nfs-ganesha-debian/issues/1 and the in-tree nfs-ganesha.spec-in.cmake (or the Fedora dist-git nfs-ganesha.spec) or https://github.com/nfs-ganesha/nfs-ganesha-debian/blob/jessie-nfs-ganesha-2.5/debian/rules

We have a growing list of miscellaneous files that don't get installed by `make install` and we have to hack up the package files to work around that. Not to mention that anyone installing by running `make install from their build tree will miss getting those files installed.

I.e.: log_rotate, dbus org.ganesha.nfsd.conf, nfs-ganesha-config.sh, mount.9P, etc., files.

**Comment by dang** [comment]
I'm wondering about this.  It's hard to imagine someone doing a full install from source and using systemd to manage it.  They'll likely use packages instead.  In addition, the more files we toss in various places around the filesystem, the harder it is do remove a ganesha that's been installed from source.

That said, I don't have a strong opinion, and it doesn't cause a problem for me, since I only ever install to a prefix, so deleting is easy.

**Comment by kalebskeithley** [comment]
nothing is going to clean up from a `make install` AFAIK.
The point is that (according to some anyway) that the packaging shouldn't have to "install" anything. It should be done by the `make install` that the packaging performs.
Packagers aren't necessarily as familiar with the software and any changes to files that need to be installed as we'd like them to be. The burden shouldn't be on them to make sure everything that needs to be installed is actually installed.

**Comment by ffilz** [comment]
Closing as will not fix.
