### ISSUE TITLE
No more lustre FSAL?

### ISSUE THREAD

**Issue by sihara** [nfs-ganesha/nfs-ganesha#198]
I can't see Lustre FSAL in next branch of nfs-ganesha.git. Anything I am missing?

**Comment by ffilz** [comment]
FSAL_LUSTRE was obsoleted and removed in favor of a future effort to make it a sub-FSAL of FSAL_VFS rather than do duplicate work to convert it to support_ex. I'm not sure what the time frame of the replacement is.

**Comment by martinetd** [comment]
To precise a bit, FSAL_VFS works pretty well with lustre - we're using that right now.
What's missing that was in FSAL_LUSTRE are lustre/HSM features to trigger async restore instead of blocking I/O threads (but with the ntirpc change spawning workers dynamically I don't know if we need it anymore), and there was a basic pNFS implementations that has not been backported to VFS (someone on IRC was interested about it and might do it)

The rest is exactly the same code. The only difference between VFS and LUSTRE was the access by handle was done through .lustre/fid so lustre could stat without opening (there is no stat by handle in VFS, you have to open then fstat) -- that wasn't worth keeping a totally different FSAL.

**Comment by ffilz** [comment]
Closing as will not fix.
