### ISSUE TITLE
NFS-RGW: unable to read bs=4m

### ISSUE THREAD

**Issue by supriti** [nfs-ganesha/nfs-ganesha#243]
[client_trace_4m_nfs.pcap.txt](https://github.com/nfs-ganesha/nfs-ganesha/files/1548199/client_trace_4m_nfs.pcap.txt)

Ceph 12.2.1/NFS-Ganesha v2.5.2

I am running fio, and for bs=4m, the read fails. In the rgw log, the error says "non-contiguous write position". But from strace and tcpdump, it does not seem to be case. Is it related to this issue: https://github.com/nfs-ganesha/nfs-ganesha/issues/204? 

Attaching the tcp dump. Github does not allow uploading pcap, so adding txt extension

**Comment by dang** [comment]
My guess is that this is related to a fundamental part of RGW, namely that it (internally) stores all data in 4M RADOS objects, so a write of >4M needs to be split.  This may not be properly implemented in librgw, causing the error.

This issues in #203 are fixed in Ceph now, to that shouldn't be it.

@mattbenjamin Any ideas?

**Comment by supriti** [comment]
Created ceph upstream tracker: http://tracker.ceph.com/issues/22783

**Comment by mattbenjamin** [comment]
@dang not immediately, but I'll dig at it

**Comment by ffilz** [comment]
Closing this due to age, feel free to re-open if it's still of interest and you have explored using a currently supported version of Ganesha (V2.8 or V3 at this time).
