### ISSUE TITLE
mdcache_find_keyed finds the entry after up_vector->invalidate() was called on this handle

### ISSUE THREAD

**Issue by antiusninja** [nfs-ganesha/nfs-ganesha#245]
Hi.
I'm implementing custom ganesha plugin. While doing that I'm looking heavily into FSAL_MEM for examples of how to do that
and sometimes to FSAL_VFS. 
One of the features of my plugin is the support of dynamicly adding and removing of top-level folders, that represent 
dynamic "sub-exports" on a single nfs share. The content in these folders can be considered random. 

I have a thread that listens on a socket and creates and removes new directories in the root folder of an export.
So what my plugin does is it sits there and listens for a command like "mkdir FOLDER_1" or "rmdir FOLDER_1"
All the exported files are also backed by a filesystem, available to ganesha. So FOLDER_1 exists both in memory structure and on a filesystem.

1. Suppose nothing was there
/export_dir/
           (NOTHING)
           
2. mkdir FOLDER_1

/export_dir
           /FOLDER_1
                    /file_1
                    /file_2

3. rmdir FOLDER_1

/export_dir
          (NOTHING)

4. mkdir FOLDER_1
5. mkdir FOLDER_2

/export_dir
           /FOLDER_1
                    /file_1
                    /file_2
/export_dir
           /FOLDER_2
                    /file_3
                    /file_4

I had zero problems implementing mkdir. But rmdir actually took a while and I need some advice.

The problem arises when I send cache invalidation request via up vector to MDCACHE layer. I expect to
have all next requests to the invalidated handle to fail with STALE error, but this does not happen.
Instead if I try some GETATTR on the invalidated handle - it can still be found in cih.

I've started digging into the problem and found out that invalidate() func is actually mdc_up_invalidate(),
and all it does is just mdcache_put(entry)->_mdcache_lru_unref()
so _mdcache_lru_unref decreases ref count by one, but it's still more than 0 (SENTINEL REF),
Apparently, if I had ref count == 0, then _mdcache_lru_unref would call mdcache_lru_clean and that
would eventually deconstruct my node and remove it from cih.
It looks like that SENTINEL REF could serve some delayed destruction purposes, but I'm not sure how it should 
work and it definately does not work in my case, because any one could come immediately after rmdir with 
same handles and find these handles in cache after their invalidation.

I've tried some things and the best I've came up with is adding mdc_unreachable() func to 
mdc_up_invalidate in the end right before mdcache_put(entry) line along with adding new invalidation flag. 

static fsal_status_t
mdc_up_invalidate(const struct fsal_up_vector *vec, struct gsh_buffdesc *handle,
		  uint32_t flags)
{
.....
  if (flags & FSAL_UP_INVALIDATE_MAKE_UNREACHABLE) //new code
    mdc_unreachable(entry); // new code

  mdcache_put(entry);
out:
	op_ctx = save_ctx;
	return status;
}

I'm using V2.5-stable branch commit 6efff50950e952a5c1a07daceeb09b27db6a7dda

So this code actually leads to immediate release and cleanup of my node. But I'm not sure.
Any comments on that case?

**Comment by mattbenjamin** [comment]
@antiusninja this post belongs on the nfs-ganesha-devel mailing list, follow links here https://github.com/nfs-ganesha/nfs-ganesha/wiki

**Comment by antiusninja** [comment]
devel mailing list link gives me 500 error.
Are you sure about that?
I've read discussions like this in other issues here.

**Comment by dang** [comment]
The important part of mdc_up_invalidate() isn't the put_ref() (that's putting the ref gotten by mdcache_find_keyed(), but clearing FSAL_UP_INVALIDATE_CACHE, which clears MDCACHE_TRUST_ATTRS, which causes mdcache_getattrs() to call mdcache_refresh_attrs(), which calls obj_ops->getattrs() in the sub-FSAL, which should return FSAL_ERR_STALE.

mdc_up_invalidate() is not intended to remove the entry from the cache entirely; it can't, because there are other refcounts on the entry, and the entry must live as long as there are refcounts.  It's intended to tell MDCACHE that the attribute, content, and dirent caches are invalid, and must be refreshed from the sub-FSAL.  The sub-FSAL can then return ESTALE, which will cause MDCACHE to remove the entry from the lookup tables (although it still won't go away entirely until the last refcount is removed).

(For the record, the development mailing list link in the wiki works for me, and leads to here:
https://sourceforge.net/projects/nfs-ganesha/lists/nfs-ganesha-devel )

I'm fine doing some discussion here, but many people on the list don't get notifications for issues on github, so you'll likely get faster response time on the list.

**Comment by antiusninja** [comment]
Thanks for the answer. I don't have experience with public discussions yet, I will start using development mailing list next time I have a question.

So, what i understood from your answer is this.
Together with calling up_ops->invalidate() I should also mark my nodes as STALE and add staleness-check in all major per-handle ops like reads writes, etc, and if they are return FSAL_ERR_STALE, that will trigger there deletion and cleanup. 
Although the cache still holds my nodes from destruction, they are already marked STALE, that means, that I may release reference to a backing file and I can just remove it from the disk, without waiting for deconstruction of node.

**Comment by dang** [comment]
Basically, yes.  What's supposed to happen is that your FSAL checks with the backing filesystem (or cluster), and determines that the backing inode has been removed, and so returns STALE.  This causes MDCACHE to mark the entry STALE, so it can't be used for anything anymore, and will be released when the last ref goes away.

Since you're using MEM as an example, the equivalent of this in MEM is that no dirent points to the object.  If you look at mem_getattrs(), you'll see that it checks to see if there are no dirents pointing to it, and returns STALE.  (Note, we special case the export object itself, since that has to remain as long as the export exists.)

Also note that some operations must still succeed on removed files.  For example, if a file is open, you can still read and write to it, even after it's removed, until it is closed.  This is a requirement of POSIX, that NFS maintains.  If your backing filesystem is a POSIX filesystem, you may get this for free.

**Comment by ffilz** [comment]
Closing this due to age, feel free to re-open if it's still of interest and you have explored using a currently supported version of Ganesha (V2.8 or V3 at this time).
