### ISSUE TITLE
open_fd_count not always decremented when needed

### ISSUE THREAD

**Issue by dirk1730** [nfs-ganesha/nfs-ganesha#286]
@dang This causes issue 280 after testing for a while.

v2.5.5, NFS3, no support for extended operations
Config file: Cache_FDs = True but also when Cache_FDs = False

Adding some logging to the code learned me that open_fd_count in _not_ decremented in:

- fsal_commit (after closing file)
- fsal_rdwr (after closing file)

open_fd_count is decremented in:

- fsal_close (not used for NFS3 I believe)
- fsal_reopen_obj (but correctly followed by increment)
- fsal_open (after reopen)

**Comment by dang** [comment]
So, this means you're using a FSAL that doesn't have support_ex().  Which FSAL is this?  I'm not surprised FD accounting is broken without support_ex(); it was untested, even in 2.5, and is gone entirely in 2.6.

**Comment by dang** [comment]
support_ex() provides quite a few advantages, including atomicity on more operations, and fewer ops in general (since getattr() is combined with other ops in several circumstances).  All in-tree FSALs were converted in 2.5, but the compatibility code was left in place, so out-of-tree FSALs could be converted.  However, since all in-tree FSALs were converted, no testing of the compatibility code was possible, so it's likely bugs crept in.

It's possible to fix that code, but unlikely, unless someone provides patches, since we have no way to test it.

In the future, you're FSAL will need to be converted to support_ex() anyway, to work with 2.6 and later, so it may be better to just do the conversion now.

**Comment by dirk1730** [comment]
OK, we will update our FSAL.
Can you explain to me the impact of `Cache_FDs = False;` in the config file?
Thx.

**Comment by dang** [comment]
Hmm... It looks like it doesn't really do anything, and hasn't since 2.4.  Before that, FDs weren't really closed when close was called, unless there were too many open; instead, they were left for the LRU thread to close.  Now, when close is called, the FD is closed.  So we essentially behave as if Cache_FDs was always false.

(Note, this doesn't mean FDs aren't kept open for anonymous I/O; that still happens, apparently regardless of that setting, even in 2.3)

**Comment by dirk1730** [comment]
Closing issue. It is probably fixed when using extended operations.
