### ISSUE TITLE
FSAL plugin development

### ISSUE THREAD

**Issue by dhthong92** [nfs-ganesha/nfs-ganesha#299]
Dear sir, I want to build a new FSAL plugin for my own database but I couldn't find out any instructions about it. I've already taken a look into FSAL source codes but it was really complicated to be understand easily. Could someone give me a hint? Where should I start if I want to build a FSAL module?

**Comment by dang** [comment]
So, there are three sets of APIs that need to be implemented in a FSAL: Module ops, Export ops, and Handle ops.  All are defined and documented in include/fsal_api.h

Module ops set up the entire FSAL module, and are used for moudle lifecycle (at start-up and shutdown), for loading new exports using that FSAL, and for pNFS (if you do that).

Export ops operate on an export, and do things like handle conversion, and determining what options the export supports.

Handle ops operate on an object handle (a file, directory, symlink, and so on), and perform all the normal operations you'd expect on file, such as read, write, open, close, unlink, and so on.

Each API function is fairly well documented in include/fsal_api.h, and each FSAL implements it.  Probably the easiest FSALs to look at are FSAL_RGW or FSAL_GLUSTER.  FSAL_VFS is complicated by the fact that it's actually multiple FSALs sharing code, so it may not be best to look there.

Feel free to drop by the mailing list or IRC if you have questions.

**Comment by dhthong92** [comment]
Dear sir, I looked at FSAL_VFS and saw that you use a `file_handle` structure to serialize the handle to pass around. I've search a lot but can't find any definition in details of that structure. As I know up to know, in x64 architecture, the `handle_bytes` will be 8 bytes in total and the first 4 bytes of `f_handle` will represent for the `inode` of the path, but I wonder what is the meaning of the rest 4 bytes? Could you explain for me a little bit?

**Comment by dhthong92** [comment]
Dear sir, I looked at FSAL_VFS and saw that you use a file_handle structure to serialize the handle to pass around. I've search a lot but can't find any definition in details of that structure. As I know up to know, in x64 architecture, the handle_bytes will be 8 bytes in total and the first 4 bytes of f_handle will represent for the inode of the path, but I wonder what is the meaning of the rest 4 bytes? Could you explain for me a little bit?

**Comment by dhthong92** [comment]
Dear sir, I looked at FSAL_VFS and saw that you use a file_handle structure to serialize the handle to pass around. I've search a lot but can't find any definition in details of that structure. As I know up to know, in x64 architecture, the `handle_bytes` will be 8 bytes in total and the first 4 bytes of `f_handle` will represent for the `inode` of the path, but I wonder what is the meaning of the rest 4 bytes? Could you explain for me a little bit?

**Comment by dang** [comment]
So, the file_handle struct in include/os/linux/fsal_handle_syscalls.h is specific to the Linux implementation of VFS, and it represents a kernel file handle used in the *_at() set of syscalls in linux.  It's not relevant to any other FSAL, including the FreeBSD version of FSAL_VFS.  Unless your FSAL is actually running on top of a linux filesystem, you won't need it.  And, if your FSAL is running on top of a linux filesystem, it should probably be a sub-FSAL of FSAL_VFS, rather than re-implementing everything.

For the record, the canonical definition of struct file_handle is in /usr/include/bits/fcntl-linux.h and you can find more information about it in the man page for name_to_handle_at or open_by_handle_at

**Comment by dhthong92** [comment]
Thanks for your reply. Currently, I'm implementing a FSAL for my own database and I try to re-implement all the methods of FSAL_VFS that work with linux filesystem to work with my database API instead. Everything worked well but I got stuck when I try to replace the file handle as I mentioned above. I've re-implement the way that `vfs_open_by_handle`, `vfs_name_to_handle` and `vfs_fd_to_handle` work but it seem like be called elsewhere and does not work as I expected. I also took a look at FSAL_CEPH but still confused about FSAL workflow. Do you have any idea?

**Comment by dang** [comment]
NFS has a concept of a handle.  This is an opaque (to the client) thing that points to some filesystem object: A file, a directory, a symlink, a block device, and so on.  The handle must be sufficient to locate and operate on that object, without anything else.

In Ganesha, this concept is implemented as the obj_handle.  This handle contains enough information for the FSAL that owns it to find the object, and contains the API used to operate on that object.  What this information is depends on the FSAL, and it's underlying filesystem.  For VFS, it's a kernel file handle.  For Ceph, it's a vinode.  For MDCACHE, which is stacked on top of another FSAL, it's a pointer to the sub-FSAL's obj_handle.

For your FSAL, this would be whatever information is necessary to find that particular object.  So, maybe it's a database handle and a key to lookup an object in the database.   Or, if your DB has persistent handles, maybe it's a persistent handle.

You won't be using the same data structures as any other FSAL, because the data you need depends on how your FSAL accesses it's filesystem.  You will have something that's equivalent to VFS's struct file_handle, but you won't actually use that structure; it only works for FSAL VFS.

**Comment by dhthong92** [comment]
Thanks @dang . With your help I finally found out the way to implement the custom handle for my FSAL. 

Everything seems okay now. But I face another problem: whenever I've updated/changed objects in my source database, how NFS know that to update/sync the changes in mounted folder? I only see NFS call to `lookup` function in handle each time I refresh the root of the mounting, but when I refresh or access to sub-directory, it didn't call to that function as I expected.
