### ISSUE TITLE
Poor performance

### ISSUE THREAD

**Issue by taich001** [nfs-ganesha/nfs-ganesha#312]
I configured ganesha to export cephfs to vmware vsphere. In vsphere center I can add the Ganesha export as a DataSore and use it for virtual disks with my virtual machines.

The performance on this virtual disks for large data transfers is good, but I have very poor performance with small files and databases.

Does anyone have an idea how to sort this out?

**Comment by dang** [comment]
So, there are some potential issues here.  First, Ganesha's performance on CephFS should be comparable to native CephFS performance, up to the capacity of the ceph MDS.  This is because all Ganesha I/O goes through the Ceph MDS, rather than being distributed to the OSDs (work on pNFS that's currently underway should mitigate this issue, but it's not ready yet).  So, as long as your MDS isn't overloaded, Ganesha should perform reasonably well.

Are small I/Os okay using native CephFS? Maybe you have a cluster tuning issue?  Or maybe your MDS is busy?  Small I/O results in lots of metadata operations, compared to large I/O, as things like modification time and file size need to be updated once-per-I/O.  So if your MDS is loaded with-respect-to metadata operations, small I/O will suffer compared to large I/O.

Small I/O is also much more sensitive to network latency than large I/O is, since it involves more round trips per byte, due to small packet sizes and the above mentioned metadata operations, so network latency tends to pile up on small I/Os.

Another feature that's being worked on is NFSv4 delegation support for FSAL_CEPH, which should help the small I/O case, due to reduction in metadata operations.

**Comment by taich001** [comment]
After testing serveral configs I still have poor performance with small IO.

The setup I have:
3 Ceph nodes each 16GiB RAM, 4GiB SSD, 10GB network
When mounting cephFS from linux host performance is ok.
When mounting NFS-Ganesha V4.1 from linux host performance poor.
When mounting NFS-Ganesha V3 from linux host performance poor.
When mounting NFS-Ganesha V4.1 from vsphere esx host performance poor.
When mounting NFS-Ganesha V3 from vsphere esx host performance poor.

The performance test I did, was to import a mysql database with 800k data and it took about 9 minutes to do that.

mysql -e "create database test;"
sync ; time sh -c "mysql test < out.sql  && sync"

real    8m55.059s
user    0m0.066s
sys     0m0.052s

**Comment by ffilz** [comment]
We are currently exploring performance. This may be addressed by future work, otherwise, since this is old, I am closing it.
