### ISSUE TITLE
should it return error when founding no released lock entry in closing a file?

### ISSUE THREAD

**Issue by fun4u** [nfs-ganesha/nfs-ganesha#316]
In nfsv4.1, when we want to close a locked file without unlocking it, ganesha will return Error to client.
Should we release all lock entries related to this open and return NFS4OK to client instead of returning error?

**Comment by dang** [comment]
From RFC 5661:

The CLOSE operation removes all share reservations held by the open-
   owner on that file.  If byte-range locks are held, the client SHOULD
   release all locks before sending a CLOSE operation.  The server MAY
   free all outstanding locks on CLOSE, but some servers may not support
   the CLOSE of a file that still has byte-range locks held.  The server
   MUST return failure, NFS4ERR_LOCKS_HELD, if any locks would exist
   after the CLOSE.

So Ganesha is fine in this, and the client should be unlocking before
closing.  We could close the locks ourselves, but since we don't, the error
is correct.

Daniel

**Comment by ffilz** [comment]
Yea, we could release the locks. I chose to be lazy when I wrote the code…

 

If someone wanted to implement this (it actually would be pretty simple – though I think it needs to walk the entire list of locks for the file), I would welcome such a patch.

 

Frank

**Comment by ffilz** [comment]
Closing this as a will not fix.
