### ISSUE TITLE
DBUS: return export id list of a nfs client

### ISSUE THREAD

**Issue by taoCH** [nfs-ganesha/nfs-ganesha#323]
Hi, 

With dbus we can actually get the list of nfsclient, and also the list of the export which proposed by nfs server. 

I wonder if it is meaningful to add a new feature to dbus, with which we can get the export id of a nfs client, to shows which export he is currently using.

Thanks for attention

**Comment by ffilz** [comment]
We do not track which exports an NFS client is using.

For NFS v3 there is the MNT_DUMP RPC, however, we don't bother supporting that because it just gives misleading information.

Clients regularly mount but don't unmount. This gives the impression that an export is in use by a client is no longer using the export. This may happen because the client crashed, or there was a network outage and the client's admin got tired of df hanging so did umount -f, or it may just be a lazy client that doesn't bother EVER sending unmount.

Servers restart and the clients continue to use their handles without pause. The clients don't need to send a new mount request.

The best we could do is perhaps keep the latest export used by a given client in struct gsh_client. Perhaps we could even be smart and exclude FSAL_PSEUDO exports. We can't just exclude export_id 0 or pseudo = "/" exports because it is valid to explicitly configure an export with pseudo = "/" (which need not have export_id 0) with any FSAL. We could even track if the use was v3 or v4 (and even the minor version).

Doing that would be a minor hit each time we processed a file handle in a request.

Note that this simple implementation would not be useful for server environments where there actually are multiple exports that might be used by a client.

More complex (and more impact because it would require a rw lock) would be a list of all the exports ever used by a client. But that then has it's own misleading nature, in a multi-export environment, a client may have briefly visited some export, but hasn't used it in days.

All of this has to be done with just export_id since exports may be removed and we don't want to hunt all the clients that used an export before removing it.

**Comment by taoCH** [comment]
Ok I see, Thanks for your reply in detail. issue closed
