### ISSUE TITLE
NFS-Ganesha Ceph HA Capability RADOS_KV

### ISSUE THREAD

**Issue by squarejester** [nfs-ganesha/nfs-ganesha#325]
My setup uses 2 dedicated servers for running NFS-GANESHA with PACEMAKER and Corosync.

I ran into problems with NFS HA of CephFS mounts. Everything works great until you try to fail over one of the NFS-Ganesha servers. When I fail over either manually or by rebooting a server I lose my NFS session. I have included the file for reference. This is from a test Ceph cluster I have built for working out problems before implementing in production. 

[ganesha.conf.pdf](https://github.com/nfs-ganesha/nfs-ganesha/files/2283925/ganesha.conf.pdf)

I'm assuming I have either not been successful in configuring support for this in the ganesha.conf file or need to do something with RADOS_KV with NFS-Ganesha and Ceph. 

According to the NFS-GANESHA GITHUB WIKI, Ceph HA cluster support is expected in nfs-ganesha version 2.7.

**"https://github.com/nfs-ganesha/nfs-ganesha/wiki/NFS-Ganesha-and-High-Availability

FSAL Ceph: With version 2.5.5 and above, RADOS_KV backend has been introduced. Work in underway for 2.7 to have clustering support in NFS-Ganesha for cephfs."**

Is clustering support for Ceph still expected to be in 2.7? I checked all the development version notes and didn't see any mention of it.

Also lacking that, is there a way to use RADOS_KV to handle client states for NFS connections (this is what I'm assuming is the issue)? Are there config examples of how to do this?

**Comment by dang** [comment]
Yes, clustering support for Ceph is included in 2.7-rc.  It's been developed and tested on kuberneties, rather than with pacemaker/corosync, but it should be usable.  I'll ping Jeff, as he's done the work.

**Comment by jtlayton** [comment]
To be clear, you're trying to run two ganesha servers in parallel? RADOS_KV won't work in an active/active configuration. It uses a hardcoded set of object names and you'll have two servers competing to add records there.

Also, proper active/active serving requires that the servers coordinate the NFS grace period, and that's not done with RADOS_KV. That is currently a work in progress (and will hopefully land in v2.7).

**Comment by squarejester** [comment]
Thanks for the quick response guys! I very much appreciate it. No, I'm trying to run active/passive just for HA but I would like to keep the NFS connections (being used by virtual machines) working when one of the 2 NFS-Ganesha servers fail or need maintenance. If I can use RADOS_KV to do that I would really appreciate some guidance on how to set that up.

**Comment by squarejester** [comment]
Ok. I discovered the main issue I was having is that I was running a version older than 2.5.5. Now I have the 2.6.2 version running. Will try to setup RADOS_KV myself.

**Comment by jtlayton** [comment]
Basically you'll just want to manage it as you would a single server. If there is only one ganesha running then it's just a matter of taking it down on one node and starting it up on another.

Also, unless you're dealing with the ip addr takeover dbus calls, you should probably use the rados_ng recovery backend driver instead of rados_kv. It's configured via the same RADOS_KV recovery block as the rados_kv driver, but is more fault tolerant than the older rados_kv driver, particularly in situations where failover may occur before the grace period ends.

**Comment by squarejester** [comment]
Any idea where in the source code the change needs to be made enable librados with ganesha.nfsd ??? I've looked and I can't seem to find what needs changing. The only thing I saw was that the RGW FSAL is disabled but I'm assuming ganesha.nfsd communicates directly via librados instead of using RGW. Am I wrong on this?

**Comment by jtlayton** [comment]
Try -DUSE_RADOS_RECOV=ON option to cmake. It should however automatically enable the rados backends if you have the correct libraries and headers installed.

**Comment by squarejester** [comment]
Line 375 of the source code already has this....

**option(USE_RADOS_RECOV "Enable Rados KV Recovery" ON)**

shouldn't this tell cmake the same thing as passing -DUSE_RADOS_RECOV=ON  ???

I think its the same thing but I'm not sure if that is the issue here. 

The log files tell me that I have an unknown recovery backend when I set this option inside the nfs-ganesha.conf file...

The message goes away if I comment it out and nfs-ganesha starts up. From the previous post I cited, it seems that ganesha.nfsd is not using librados shared library and therefore can't communicate to ceph. Am I off here?

NFSv4
{
           **RecoveryBackend = rados_ng;**
}

**Comment by dang** [comment]
We have our CMake set up so that most things are on by default, but are disabled if the relevant libraries and headers are missing.  You can look at the output of CMake at the end, we print the results for every option.  If RADOS_RECOV is off, you can look back through the CMake output to see what libraries/headers are missing.

**Comment by squarejester** [comment]
Ok, thanks. I am going to try a build from source on a clean identical test machine and see what happens. The problem from what I can see from the source code is that is that is looking for rados/librados for that and it is installed on my machine but it doesn't seem to find it. I will let you know the results of what I find.

**Comment by jtlayton** [comment]
You'll need the development headers to build it. On Fedora/RHEL that's the librados-devel, not sure on other distros though.

**Comment by stef97** [comment]
Hi,
On your wiki, you are saying ver 2.7 will provide clustering CEPH support without Linux HA
" ...Work in underway for 2.7 to have clustering support in NFS-Ganesha for cephfs .."

Could someone please clarify what is included in 2.7 and, more importantly, how do we use it 
as it appears RAdos_KV still needs Linux HA  ( see below)?

https://archive.fosdem.org/2018/schedule/event/cephfs_gateways/attachments/slides/2636/export/events/attachments/cephfs_gateways/slides/2636/cephfs_samba_and_nfs.pdf

Many thanks

**Comment by dang** [comment]
HA requires something to manage it.  That is, something has to track availability of services, and take action when they're no longer available.  Traditionally, this has been pacemaker/corosync or ctdb, and those will continue to have a place in the HA landscape of Ganesha, especially on bare metal.

However, in a containerized environment, the orchestrator (such as kuberneties) can also fulfill this role.  The rados-ng backend can work with kube to handle HA in a new way.  Instead of failing clients over to another Ganesha instance, this environment will put the cluster into grace, and then start a new Ganesha pod with the same identity (IP, config, and so on) as the failed one.  Clients will then re-connect to this new pod and recover, and grace will exit.  This allows simpler handling of HA, since virtual IP handling isn't necessary, and maintains load balancing, since clients don't migrate to an existing node.

@jtlayton has been working on this.

**Comment by stef97** [comment]
Many thanks for explaining this
How about in a VMWare / ESXi environment  ?

Apparently NFS4.1 allows mutipathing and load balancing
https://cormachogan.com/2015/02/04/vsphere-6-0-storage-features-part-1-nfs-v4-1/

Can I simply deploy 2 Ganesha instances with rados-KV  ?
Is there a tutorial for deploying rados-kv as I was not able to have 2
servers working together
 ( i.e deployng one server with rados-kv worked fine but the second one did
not provide any NFS shares )

Steven

**Comment by squarejester** [comment]
Exactly my question too. What about bare metal or virtual environments? Do we still use pacemaker? 

Sean

**Comment by jtlayton** [comment]
Yes, you'd need to use pacemaker or something to manage starting the daemons, IP addressing, etc.

The rados_kv backend is not designed for active/active clustering. That's why we've added the new rados_cluster backend. What rados_cluster backend gives you is the ability to run multiple servers in parallel and have them coordinate their grace periods.

Unfortunately, there's no tutorial as of yet. I should probably write one up...

**Comment by dang** [comment]
Unfortunately, that URL doesn't describe how VMWare does multipathing/loadballancing, or what it expects of the server, so I don't know if it can help in this circumstance.  Certainly it won't help Ganesha be HA for general clients; but if all clients are VSphere, it may be enough, I don't know.

**Comment by stef97** [comment]
I've checked the config_samples for ver 2.7 RC4 and couldn't find any
reference to rados_cluster , only rados_ng and rados_kv
Is this feature available in a different version ?

Also,if time permits, it will be useful to post some case scenarios ( when
to use _KV, _NG and respecitvely _cluster recoverybackend)

Many thanks for your prompt responses

Steven

**Comment by fiskn** [comment]
I'm also really interested in this.

From what I can see in the doc and going through the rados_cluster commit, there a few things that need to be configured

1. Create required RADOS pools for grace tracking
2. Complete ganesha config pointing at CephFS pool with recovery method as rados_cluster pointing at pool in #1 
3. Use the rados grace tool to populate the shared grace object with the ganesha nodes
4. Use LVS/HAProxy to health check and load balance between the ganesha instances

I'm not understanding the requirement of K8's or pacemaker here, as long as I am responsible for keeping at least 1 instance of ganesha up and running manually.  Would love to understand more if I'm wrong.

**Comment by jtlayton** [comment]
There's no requirement to run k8s or pacemaker. You can certainly manage the ganesha.nfsd daemons by hand (and I regularly do so in order to test functionality).

Note too that LVS/HAProxy could be problematic. If a client got shifted off to a different server, it can't currently reclaim. Any migration at this point must be done manually (i.e. unmounting and remounting the share via a different address).

**Comment by fiskn** [comment]
Thanks for confirming.

Ah, I see. Does that still apply even if the reason for migration is due to a ganesha server going offline? Not having to run a seperate HA stack and instead providing active/active really appeals.

**Comment by jtlayton** [comment]
Yes. Currently we don't split and merge recovery databases, and that would need to be done in order to have that work. You need to be able to resurrect the same server with the same nodeid and address. Most (all) of the storage for that server can live in RADOS though. Eventually, we'd like to do some sort of live migration, but it's a bit more work.

**Comment by olifre** [comment]
What about NFS 4 migration, i.e. via `NFS4ERR_MOVED` for the case a server is taken offline on purpose (e.g. for kernel updates etc.)? 
While this is not "HA" in the classical sense, it is likely much easier to support in Ganesha itself - correct?

**Comment by jtlayton** [comment]
Yes, that's what I meant by live migration. There is already some migration support in ganesha and I had some draft patches at one point that could declare an export on a ganesha server as "moved" such that it would start returning NFS4ERR_MOVED.

To do that right, you'd really need to add fs_locations_info support to ganesha.

**Comment by parametriq** [comment]
So, what's the recommended half-decent architecture currently? Having some "quickstart guide" or "best practices" for clustering Ganesha for CephFS would be very helpful to understand the solution in a nutshell to further plan a lab or prod environment

**Comment by jiang4357291** [comment]
>  The rados-ng backend can work with kube to handle HA in a new way.

Is ther any tutrioal for this ?

**Comment by jtlayton** [comment]
Only the blog post here (which has terribly mangled formatting, unfortunately):

https://ceph.com/community/deploying-a-cephnfs-server-cluster-with-rook/

**Comment by ffilz** [comment]
Closing as resolved.

Note that as a question, this would have been a better subject for the support mailing list, support@lists.nfs-ganesha.org
