### ISSUE TITLE
question: interaction of ganesha with a standard nfs server

### ISSUE THREAD

**Issue by Boran** [nfs-ganesha/nfs-ganesha#363]
Hi,

I have a an existing Debian jessie NFS server running fine, that also access some cephfs mounts, but it cannot export the cephs mounts via NFS. 
Apparently nfs-ganesha-ceph can do this.

Presumably, if nfs-ganesha is installed, the existing NFS packages have to be removed as nfs-ganesha-ceph replaces the "standard" nfs server in Debian?
Is nfs-ganesha a drop-in replacement?
Will existing NFSv3 and v4 exports continue to work (/etc/exports syntax, ext4 backend)?

Notes
 - Debian jess is 8.11, Linux 4.9.0-0.bpo.5-amd64)
 - Have read the ceph page, https://github.com/ceph/ceph/blob/master/doc/cephfs/nfs.rs and found debian packages https://packages.debian.org/search?keywords=nfs-ganesha)

(Apologies in advance if this non-code related question should not be asked here..)

**Comment by dang** [comment]
Ganesha isn't a drop-in replacement, it has it's own config (in /etc/ganesha/ganesha.conf).  It has almost all the capabilities of knfsd (it's missing pNFS support), but you'll have to translate the config over.

Now, you could run Ganesha with knfsd for nfsv4 only, by changing the port that Ganesha's running on.  This won't work for v3, since that uses portmapper.

**Comment by Boran** [comment]
Great, thanks for the clear infos.
