### ISSUE TITLE
NFS synchronization mechanism

### ISSUE THREAD

**Issue by dhthong92** [nfs-ganesha/nfs-ganesha#385]
I try to impement a custom FSAL for my own database but I face a problem: whenever the objects in my database updated, how NFS could know the changing event from source to reload/ refresh the mounting? I’ve tried to test many built-in FSAL like VFS or MEM but I see that it only invokes the `lookup` function in `handle part` when I refresh the root path of the mounting, not happen when I refresh the sub-directory as expected. So I wonder how does the synchronization mechanism of NFS from source to mounted point work? Did I look to the right function? Hope you could explain for me a little bit. Really appreciate your help!

**Comment by dang** [comment]
To handle this, Ganesha has a set of UP calls.  The upcall framework allows the FSAL to send async notifications to MDCACHE to tell it when things have changed.  MEM doesn't use this directly (nothing can change it) but it does have a testing framework that sends upcalls at random, so that we can test that upcalls work properly.  You can look at FSAL/FSAL_MEM/mem_up.c to see it's uses.

FSAL_GLUSTER has proper support for upcalls, and uses them extensively.  You can take a look at FSAL/FSAL_GLUSTER/fsal_up.c to see it's implementation.

What these upcalls basically do is indicate to MDCACHE that a specific object has been updated, so that MDCACHE invalidates it's cache entry for that object.  Then, the next time the object is accesses, it calls into the FSAL for that operation (lookup, or whatever) and gets the new data.

**Comment by ffilz** [comment]
This is a question that would have been better directed to the development mailing list devel@lists.nfs-ganesha.org since the question has been answered I'm going to close this.
