### ISSUE TITLE
HowTo crossmount a directory using GLUSTER FSAL

### ISSUE THREAD

**Issue by giminni** [nfs-ganesha/nfs-ganesha#400]
I could successfully export a GLUSTER volume over nfs-ganesha. Now I want to mount a loopback directory for PXE booting stuff after the exported GLUSTER volume.
I could not found any advice how to cross mount it inside the export definitions. 
Is there a way to do it like the crossmnt option inside the nfs-kernel-server?

**Comment by dang** [comment]
Just export the new FS.  We don't auto-export sub-filesystems, you need to put an export for each FS you want.  Exports don't need to be rooted in the pseudofs, they can be exported from anywhere, as long as the path to the export exists.

**Comment by giminni** [comment]
I switched to nfs-ganesha 2.5.1 on aarch64 defined a path to "/export/nfsroot/host-a" the GlusterFS volume is export I am using inside EXPORTS the volpath pointing to "/nfsroot/host-a" 
Directory host-a is created before mounting it. Then I use "/nfsroot/host-a" as the loopbackvi mount point for PXE boot. 
```
EXPORT                                                                          
{                                                                               
   Export_Id = 123; # Export Id (mandatory, each EXPORT must have a unique Export_Id)
   Path = "/repo/nfsroot/host-a"; # Exported path (mandatory)                  
                                                                                
   # Exporting FSAL                                                             
   FSAL {                                                                       
      Name = "GLUSTER";                                                         
      Hostname = server-a;                                                  
      Volume = "repo"; # Volume name                                            
      Volpath = "/nfsroot/host-a"; # Path under volume name               
      Up_poll_usec = 10; # Upcall poll interval in microseconds                 
      Transport = tcp; # tcp or rdma                                            
   }                                                                            
                                                                                
   Pseudo = "/repo/nfsroot/server-a";  # Pseudo Path (required for NFS v4)               
   Access_Type = RW;          # Access permissions                              
   Squash = No_Root_Squash;   # Allow root access                               
   SecType = "sys";           # Security flavor supported                       
}                                                                               
 ```
localhost:host-a =========> /repo/nfsroot/host-a
Then I mount a loopback device on host-a

Still doesn't load the rootFS properly.

**Comment by dang** [comment]
Okay, I think I understand what your problem is.  Ganesha is not actually exporting /repo/nfsroot/host-a from the host kernel's namespace.  Instead, FSAL_GLUSTER is a full blown Gluster client, using GFAPI to directly access the cluster.  There does not need to be a mount of that volume on the Ganesha host at all (and typically, there wouldn't be one).  So, anything you do in the host machine's kernel namespace won't show up in Ganesha, since it's not in the Gluster cluster at all.

I see several options.  First, you can do exactly what you're doing now, by loop mounting at the same point on the host machine, and then export that loop mount via FSAL_VFS at the correct point in the PSEUDO tree.   Second, since the PSEUDO tree doesn't need to be related to the export locations, you can loop mount that file to anywhere on your host, and export it via FSAL_VFS at the correct PSEUDO location.
Finally, you can extract the loop filesystem into your gluster tree, in which case it will just show up in your existing export.  This changes what it is (it's a file tree, rather than a loop mounted filesystem) but it does mean that the entire file tree is in your gluster cluster, rather than just on your Ganesha host.

**Comment by giminni** [comment]
@dang thx for point me into the right direction. Yes doing a local loopback mount from the GLUSTER directory solved the problem. I used now VFS FSAL and it works like a charme!
