### ISSUE TITLE
Why we can't disable mdcache?!

### ISSUE THREAD

**Issue by tracymacding** [nfs-ganesha/nfs-ganesha#437]

**Comment by dang** [comment]
MDCACHE provides 3 things:  An attribute cache for objects, a directory entry cache, and an object handle cache.  2 of these (the attribute cache and the dirent cache) can be disabled.  However, the handle cache cannot.

The reason is that the protocol layers depend on having stable, refcounted pointers to handles that persist for the duration of an OP.  This is provided by MDCACHE, and not by any of the FSALs.  It's theoretically possible to have a FSAL provide it's own handle cache, and then disable MDCACHE, but it's not implemented yet, and the result would be very similar to the handle cache in MDCACHE anyway, so there would be little gain.  It addition, every FSAL would need to implement this, and all of them would need to be tested fully for bugs, so it's simpler, easier, and safer to consolidate this into a single handle cache layer.  This lives in MDCACHE for now.
