### ISSUE TITLE
Multi mountpoint while change to dir under mountpoint

### ISSUE THREAD

**Issue by tracymacding** [nfs-ganesha/nfs-ganesha#440]
I use jfs as backend FSAL, and mount it like 
```
 mount -t nfs -o vers=3 -o lookupcache=none 127.0.0.1:/mnt/jfs_ganesha/ /mnt/c/
```
but when i make dir(a and n) under /mnt/c and change to the dirs made, i got multiple mountpoint like
```
127.0.0.1:/mnt/jfs_ganesha/   100P  1.0M  100P   1% /mnt/c
127.0.0.1:/mnt/jfs_ganesha/n  100P  1.0M  100P   1% /mnt/c/n
127.0.0.1:/mnt/jfs_ganesha/a  100P  1.0M  100P   1% /mnt/c/a
```

what is the possible reason?

**Comment by malahal** [comment]
maybe, automounter? Also, don't use NFSv3 with NLM for mounting locally. The kernel lockd wil take over and NLM requests won't reach ganesha on your system!  -overs=3,nolock mount options will avoid this or use NFSv4.

**Comment by dang** [comment]
This is strange, because you can't mount a subdirectory via NFSv3, only an export.  My best guess is that jfs is messing up the filesystem ID, which is causing the client to pretend there's mounts.

**Comment by ffilz** [comment]
Well, you can mount sub-directories in NFSv3.

Something is definitely happening to change the filesystem ID, that's what the Linux client uses to create the additional mounts on client side to represent the appearance of multiple filesystems from the server. 

Can you check what happens if you export the same filesystem via knfsd?

**Comment by dang** [comment]
I was unable to do so on a ganesha export.

**Comment by ffilz** [comment]
So I have the following filesystems:

/export/ext4-disk-exp1 on /export/exp1 type ext4 (rw,relatime,seclabel,data=ordered)
/export/ext4-disk-exp3 on /export/exp1/some/path/exp3 type ext4 (rw,relatime,seclabel,data=ordered)
/export/ext4-disk-exp2 on /export/exp1/some/path/exp2 type ext4 (rw,relatime,seclabel,data=ordered)
/export/ext4-disk-exp5 on /export/exp1/some/path/exp2/foo/baz/exp5 type ext4 (rw,relatime,seclabel,data=ordered)

And the following export:
EXPORT
{
  Export_Id = 380;
  Path = /export/exp1;
  Pseudo = /export/exp1;
  FSAL
  {
    Name=VFS;
  }
  Access_Type=RW;
  Squash = None;
  SecType = sys;
  Tag = exp1;
}

After I do the following:
mount 127.0,0,1:/export/exp1 /mnt
ls -l /mnt/some/path/exp2/foo/baz/exp5/
ls -l /mnt/some/path/exp3
find /mnt

I do
mount | grep 'type nfs'

And get:
127.0.0.1:/export/exp1 on /mnt type nfs (rw,relatime,vers=3,rsize=1048576,wsize=1048576,namlen=255,hard,nolock,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=127.0.0.1,mountvers=3,mountport=50997,mountproto=udp,local_lock=all,addr=127.0.0.1)
127.0.0.1:/export/exp1/some/path/exp2 on /mnt/some/path/exp2 type nfs (rw,relatime,vers=3,rsize=1048576,wsize=1048576,namlen=255,hard,nolock,proto=tcp,timeo=600,retrans=2,sec=sys,mountproto=,local_lock=all,addr=127.0.0.1)
127.0.0.1:/export/exp1/some/path/exp2/foo/baz/exp5 on /mnt/some/path/exp2/foo/baz/exp5 type nfs (rw,relatime,vers=3,rsize=1048576,wsize=1048576,namlen=255,hard,nolock,proto=tcp,timeo=600,retrans=2,sec=sys,mountproto=,local_lock=all,addr=127.0.0.1)
127.0.0.1:/export/exp1/some/path/exp3 on /mnt/some/path/exp3 type nfs (rw,relatime,vers=3,rsize=1048576,wsize=1048576,namlen=255,hard,nolock,proto=tcp,timeo=600,retrans=2,sec=sys,mountproto=,local_lock=all,addr=127.0.0.1)

This is the expected behavior if you have real filesystems sub-mounted under an export. The client creates a superblock (and thus mount) for each filesystem (which keeps find from getting grumpy about detecting loops because inode numbers are duplicated - though if you do the find BEFORE doing the ls, it does get grumpy, and the extra nfs mounts don't show up, I'm not quite sure why...). The extra mounts/superblocks create separate inode number spaces for each filesystem.

The ONLY reason the client does this is because it sees fsid changing. Note that this "automount" behavior for NFSv3 is an expansion to make it work a little more like NFSv4.

Ganesha will export all of these filesystems with the same export_id, but it incorporates the fsid into the handle as well to keep the handles unique (knfsd doesn't have export_ids, but does incorporate the fsid into the handle - note that the handle from name_to_handle_at DOES NOT include the fsid).

If you are seeing this behavior of multiple mounts on your NFS client, your server is presenting files with different fsid in the attributes.

Currently FSAL_VFS gets the FSID attribute from struct stat st_dev which MAY be different than the fsid used in the handle (which may be based on the UUID for the filesystem or may be based on st_dev).

I would look to see if JFS returns a consistent value for st_dev. If it doesn't, then we may need to adapt Ganesha some to use the fsid created from st_dev or UUID on creation of the export. I'm not quite sure why I didn't do it that way when I implemented the sub-mounted filesystem support,

If you really are not exporting multiple filesystems, you can force fsid by using the filesystem_id EXPORT option to set the fsid. This is not the greatest solution but it could resolve an issue with a filesystem that doesn't have a stable st_dev.

**Comment by tracymacding** [comment]
> So I have the following filesystems:
> 
> /export/ext4-disk-exp1 on /export/exp1 type ext4 (rw,relatime,seclabel,data=ordered)
> /export/ext4-disk-exp3 on /export/exp1/some/path/exp3 type ext4 (rw,relatime,seclabel,data=ordered)
> /export/ext4-disk-exp2 on /export/exp1/some/path/exp2 type ext4 (rw,relatime,seclabel,data=ordered)
> /export/ext4-disk-exp5 on /export/exp1/some/path/exp2/foo/baz/exp5 type ext4 (rw,relatime,seclabel,data=ordered)
> 
> And the following export:
> EXPORT
> {
> Export_Id = 380;
> Path = /export/exp1;
> Pseudo = /export/exp1;
> FSAL
> {
> Name=VFS;
> }
> Access_Type=RW;
> Squash = None;
> SecType = sys;
> Tag = exp1;
> }
> 
> After I do the following:
> mount 127.0,0,1:/export/exp1 /mnt
> ls -l /mnt/some/path/exp2/foo/baz/exp5/
> ls -l /mnt/some/path/exp3
> find /mnt
> 
> I do
> mount | grep 'type nfs'
> 
> And get:
> 127.0.0.1:/export/exp1 on /mnt type nfs (rw,relatime,vers=3,rsize=1048576,wsize=1048576,namlen=255,hard,nolock,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=127.0.0.1,mountvers=3,mountport=50997,mountproto=udp,local_lock=all,addr=127.0.0.1)
> 127.0.0.1:/export/exp1/some/path/exp2 on /mnt/some/path/exp2 type nfs (rw,relatime,vers=3,rsize=1048576,wsize=1048576,namlen=255,hard,nolock,proto=tcp,timeo=600,retrans=2,sec=sys,mountproto=,local_lock=all,addr=127.0.0.1)
> 127.0.0.1:/export/exp1/some/path/exp2/foo/baz/exp5 on /mnt/some/path/exp2/foo/baz/exp5 type nfs (rw,relatime,vers=3,rsize=1048576,wsize=1048576,namlen=255,hard,nolock,proto=tcp,timeo=600,retrans=2,sec=sys,mountproto=,local_lock=all,addr=127.0.0.1)
> 127.0.0.1:/export/exp1/some/path/exp3 on /mnt/some/path/exp3 type nfs (rw,relatime,vers=3,rsize=1048576,wsize=1048576,namlen=255,hard,nolock,proto=tcp,timeo=600,retrans=2,sec=sys,mountproto=,local_lock=all,addr=127.0.0.1)
> 
> This is the expected behavior if you have real filesystems sub-mounted under an export. The client creates a superblock (and thus mount) for each filesystem (which keeps find from getting grumpy about detecting loops because inode numbers are duplicated - though if you do the find BEFORE doing the ls, it does get grumpy, and the extra nfs mounts don't show up, I'm not quite sure why...). The extra mounts/superblocks create separate inode number spaces for each filesystem.
> 
> The ONLY reason the client does this is because it sees fsid changing. Note that this "automount" behavior for NFSv3 is an expansion to make it work a little more like NFSv4.
> 
> Ganesha will export all of these filesystems with the same export_id, but it incorporates the fsid into the handle as well to keep the handles unique (knfsd doesn't have export_ids, but does incorporate the fsid into the handle - note that the handle from name_to_handle_at DOES NOT include the fsid).
> 
> If you are seeing this behavior of multiple mounts on your NFS client, your server is presenting files with different fsid in the attributes.
> 
> Currently FSAL_VFS gets the FSID attribute from struct stat st_dev which MAY be different than the fsid used in the handle (which may be based on the UUID for the filesystem or may be based on st_dev).
> 
> I would look to see if JFS returns a consistent value for st_dev. If it doesn't, then we may need to adapt Ganesha some to use the fsid created from st_dev or UUID on creation of the export. I'm not quite sure why I didn't do it that way when I implemented the sub-mounted filesystem support,
> 
> If you really are not exporting multiple filesystems, you can force fsid by using the filesystem_id EXPORT option to set the fsid. This is not the greatest solution but it could resolve an issue with a filesystem that doesn't have a stable st_dev.

Yeah, after i set the fsid, everything got ok~
