### ISSUE TITLE
Can acl now be used to add permissions in cephfs-ganesha environments?

### ISSUE THREAD

**Issue by comosus** [nfs-ganesha/nfs-ganesha#442]
Hi,
I've been doing research for the last few days on nfs-ganesha.
My ceph's version is 14.2.xx. NFS-ganesha's version is 2.7.4..
I want to add some permissions for some anonymous users/groups through acl.. It fails.
( Use "setfacl" on the export directory in the cephfs , however it dose's work in the clients (nfs-mount) )
I find the acl in the nfs is called as nfs_acl and they are different. Could you give me some advice on how to realize this function... Thank you very much.

**Comment by dang** [comment]
FSAL_CEPH doesn't have ACL support currently.  CephFS has POSIX ACLs, which are mostly sufficient to implement NFS ACLs, but they are not made available in libcephfs.  In order to have ACLs on FSAL_CEPH, someone would need to implement ACLs in libcephfs, and then write the glue code in Ganesha to use them.  This would only give POSIX ACLs; to have full NFS ACLs, those would need to be implemented in CephFS as well.

**Comment by comosus** [comment]
@dang Thank you for your reply~
