### ISSUE TITLE
（Question）shared file can be read and writer but cannot be renamed or deleted..

### ISSUE THREAD

**Issue by comosus** [nfs-ganesha/nfs-ganesha#444]
Hello @dang,
I'm sorry to bother you again. 
I recently reviewed some product documents and found the configuration that shared files can be read and written but cannot be renamed or deleted. I think the configuration was intertsting. So I looked up some code and found that the only way to control such permissions was to rely on four flag bits "Write Read MDWrite MDRead". However it is not enough to implement that configuration.  Does that mean I need design patches to implement this functionality? Or maybe I forgot something about it.. 
My environment is ganesha 2.7.4 ceph 14.2.. Thank you ~

**Comment by dang** [comment]
This can theoretically be done with NFS ACLs.  NFS ACLs have separate permissions for read and write data, and for delete.  (rename is handled by the ACL of the parent directory, I think).  However, none of the current FSALs fully support NFS ACLs, since they're different than POSIX ACLs.  A few years ago, I wrote test code for VFS that implements full NFS ACLs by storing them in memory.  It works, but only as long as Ganesha is running, obviously.

The way to do this correctly is to implement full NFS ACLs for the FSAL you care about.  Unfortunately, this cannot be FSAL_VFS, since the kernel team has refused merge RichACLs, so there's no way to store them in a VFS filesystem.

**Comment by ffilz** [comment]
Depending on what you really needed to do, the export permissions could be enhanced to accomplish this need, though directory permissions would also work to prevent delete or rename.

Closing this as something we aren't going to make any code changes for at this time.
