### ISSUE TITLE
Can FSAL api be asynchronous 

### ISSUE THREAD

**Issue by tracymacding** [nfs-ganesha/nfs-ganesha#445]
in my own fsal, i found commit2 api(will call fsync to flush all dirty data to backend storage) costly and block the client thread, so i wonder can commit2 api be asynchronous?

**Comment by dang** [comment]
Unfortunately, no.  The NFS spec requires that a COMMIT results in data synced to stable storage before returning to the client.  This makes sense, because the client uses this to flush it's cache.  If the data is not stable, and the client flushes it's cache, and the server crashes, then the data is just lost (and the file is likely corrupted).
