### ISSUE TITLE
Vmware Issues  svmotion and vmotion

### ISSUE THREAD

**Issue by madmax01** [nfs-ganesha/nfs-ganesha#460]
HI guys,

i just renew  #386  with new Infos. Since gluster went away from nativ NFS,... we just have issues with nfs-ganesha since then. trying to get it working,..  but no chance so far.  and there is too less Infos on Net about.

- Esxi 6.7 U3
- Gluster 6.5
- ganesha 2.8.2
- ubuntu 18.04

adding an link. added the nfs3 log and nfs4 log

https://we.tl/t-HNBMn0wVVd

- NFS3  Issue

once doing a vmotion  it stucks for 1min then continue  (happens only with ganesha). normally vmotion takes few secs. with nfs4 and old gluster works in few secs.
NFS3   Svmotion started =  14:47:20
NFS3   vmotion started = 14:49:30 

-NFS4 Issue

not possible to svmotion poweredOn VM onto Storage.  Only offline vm works.   or an online vm but with Snapshot.

once moved offline > then could start it and vmotion works. doesn't have the condition like NFS3.
-----------------------------

So both Protocols have Issues.

Happy if anyone could have a look

thx

Max

**Comment by soumyakoduri** [comment]
Hi,

Sorry for the delay. To start with could you please provide following information -
* On each ESXi node, do you use different IP's to mount NFS share? The reason I am asking this is because Gluster-NFS by default doesnt configure HA. So if you are not keen on using active-active HA NFS-Ganesha server, then you could probably turn off below option -

#gluster v set <volname> features.cache-invalidation off

* Also please configure the grace period to lower value in nfs-ganesha.conf file and restart the NFs server

NFSv4 {
Grace_Period = 15
}

* Could you provide logs and packet trace when the issue happens for both NFSv3 and NFSv4 (collected separately).

**Comment by ffilz** [comment]
Closing this due to age, feel free to re-open if it's still of interest and you have explored using a currently supported version of Ganesha (V2.8 or V3 at this time).
