### ISSUE TITLE
Linking dbus server symbols

### ISSUE THREAD

**Issue by NateThornton** [nfs-ganesha/nfs-ganesha#481]
Upgrading to 2.8 from 2.5 and my fsal fails to load because of linking failure to dbus symbols

`2019-09-18T11:19:11.695536+0000 29549[dbus_heartbeat] load_fsal :NFS STARTUP :FATAL :Could not dlopen module: /opt/test/lib64/ganesha/libfsalatafs.so Error: /opt/test/lib64/ganesha/libfsalatafs.so: undefined symbol: dbus_status_reply. You might want to install the nfs-ganesha-TESFS package`

On 2.5 the dbus symbols were included
```
$ nm ./build/MainNFSD/ganesha.nfsd | grep dbus
000000000054a15f T add_dbus_broadcast
000000000045b45a t admin_dbus_get_grace
[...]
```

but this is no longer the case on 2.8
```
$ nm ./build/ganesha.nfsd | grep dbus
0000000000604238 B gsh_dbus_thrid
```

Any help would be appreciated.

**Comment by kalebskeithley** [comment]
Starting with 2.8, most of the the ganesha.nfsd is actually in a shared lib
(e.g. /usr/lib64/libganesha_nfsd.so.2.8 on Fedora- and RHEL-like
distributions) which is where you should search for symbols.
/usr/bin/ganesha.nfsd is now just a small wrapper executable that consists
solely of main(). (Pretty sure this is mentioned in the 2.8 release notes.)

Your FSAL needs to be rebuilt, and linked with libganesha_nfsd.

And since none of the in-tree FSALs calls dbus_status_reply() we didn't
know it needed to be exported from the shared lib (in
.../src/MainNFSD/libganesha_nfsd.ver) so you'll need to fix that too when
you build/rebuild.

--

Kaleb

**Comment by NateThornton** [comment]
Thanks Kaleb, I got it working with your advice.

Is there a good way to patch in the necessary exports into .../src/MainNFSD/libganesha_nfsd.ver for our FSAL?

**Comment by kalebskeithley** [comment]
On Wed, Sep 18, 2019 at 10:41 AM Nathaniel Roiger <notifications@github.com>
wrote:

> Thanks Kaleb, I got it working with your advice.
>
> Is there a good way to patch in the necessary exports into
> .../src/MainNFSD/libganesha_nfsd.ver for our FSAL?
>
You can just edit the file in source tree. If you're building rpms you can
cobble up a patch file and add it to the nfs-ganesha.spec file that you're
using to build with.

Otherwise I'm not sure what you're asking.

And are there any other calls besides dbus_status_reply() that need to be
exported for your FSAL? (See
https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/468728)

--

Kaleb

**Comment by NateThornton** [comment]
I think dbus_status_reply() is it. Will close. Thanks.

**Comment by NateThornton** [comment]
Found a couple more:
```
  gsh_dbus_register_path;
  gsh_dbus_broadcast;
```
