### ISSUE TITLE
name_to_handle_at is failing in docker: cannot export NFSv4

### ISSUE THREAD

**Issue by maxlapshin** [nfs-ganesha/nfs-ganesha#511]
Systemd has the same problem:

https://github.com/systemd/systemd/pull/5499

What do I get:

`EXPORT
{
	Export_Id = 0;
	Path = /var/roots;
	Pseudo = /;
	Access_Type = RO;
	Protocols = NFS4;
	Transports = TCP;
	Disable_ACL = TRUE;
	Squash = no_root_squash;
	FSAL {
		Name = VFS;
	}
}

NFS_Core_Param {
	Protocols = 4;
	Transports = TCP;
	Enable_RQUOTA = false;
	Enable_UDP = false;
}

`

and ganesha shows:

`
24/11/2019 04:01:05 : epoch 5dda0081 : 36cdbe7b18b8 : nfs-ganesha-11[main] vfs_lookup_path :FSAL :CRIT :Could not get handle for path /var/roots, error Operation not supported
24/11/2019 04:01:05 : epoch 5dda0081 : 36cdbe7b18b8 : nfs-ganesha-11[main] init_export_root :EXPORT :CRIT :Lookup failed on path, ExportId=0 Path=/var/roots FSAL_ERROR=(Operation not supported,95)
`

Seems that  it is too hard to make it available in docker. Is it possible to allow it to fail?

**Comment by dang** [comment]
If you're running in a container, you need to have a privileged container.  This works for me (or did a year ago when I last did it).

**Comment by maxlapshin** [comment]
It doesn't work today.

I tried --privileged, seccopm=un....,  cap-add and all other options.

It just doesn't work in Nov 2019 Docker.

I suppose that idea of userspace only NFS server should be aware of docker.  I'd like to help, but I do not understand what does this name_to_handle_at does and what is it for.

**Comment by maxlapshin** [comment]
I've understood the problem. It is not about permissions.

It is about overlayfs which is mandatory in Docker.

Error is "Operation not supported", so it is impossible to allow it.

Is it possible to somehow enable it?

**Comment by malahal** [comment]
Recently, I tried with bind mounts on centos8 and it worked fine (I used
GPFS fsal, but should be similar). The docker version I tried on centos8
is 1.0.5, don't know how different your docker version is though.

**Comment by maxlapshin** [comment]
I’m using Docker desktop  2.1.0.5 and default docker.io <http://docker.io/> in Ubuntu 18.04

**Comment by dang** [comment]
open_by_handle_at() is a systemcall that is used to convert a handle to a file descriptor.  This allows the opaque binary wire handle that NFS uses to send to the client to work.  It is absolutely necessary for NFS to work at all.  If a filesystem (overlayfs in this case) doesn't implement open_by_handle_at(), then it cannot be exported by NFS (and I believe this even holds true for knfsd).

**Comment by maxlapshin** [comment]
well, this sounds a bit strange.

Samba or webdav will work, but NFS cannot?

**Comment by dang** [comment]
Webdav is stateless, and operates entirely on filenames.  NFS is stateful, and defines a on-wire handle that needs to have certain properties.  I don't know the SMB protocol well enough to comment, it may also need open_by_handle_at().  This is a design choice made when NFS was defined as a protocol.

open_by_handle_at() has been a supported part of the linux kernel since 2011.  Filesystems should support it by now.

**Comment by maxlapshin** [comment]
Why nfs server cannot live with just open/pread?

**Comment by ffilz** [comment]
Just to clarify... The need for open_by_handle_at is not because NFS is stateful, it's actually because of the part of NFS that is NOT stateful.

The way NFS accesses a file is to do a LOOKUP by name which produces a handle, specifically, the LOOKUP is by path component name, using the handle of a parent directory. In NFS v3, the MOUNT protocol is used to lookup an initial handle from a fully qualified path, in NFS v4, a Pseudo File System is implemented that implements a file system tree leading to the various exports, and a PUTROOTFH operation exists to produce the initial handle. NFS v4 also introduces the statefull OPEN operation that combines a LOOKUP with instantiating an open state that consists of access and deny modes (compatible with CIFS) and managing atomic exclusive file creation (and also delegations).

All other operations use the handle to access a file.

The trick is that NFS is partially not statefull (NFS v3 without using byte range locks is completely stateless), so after a server reboot (and losing ANY transient information), the server must be able to take a file handle provided by a client and access a file. It no longer has a filename or the fully qualified path to the file.

The open_by_handle_at system call takes this filehandle and passes it to the filesystem (referenced by the open file descriptor that is the parameter to open_by_handle_at that is the "at" parameter). This is actually a pretty thin wrapper around the "exportfs" interface that knfsd uses to reference an inode given a handle. There is a companion system call, name_to_handle_at that takes a file descriptor of a parent directory and a name and returns a handle that basically implements LOOKUP, though it take the AT_EMPTY_PATH option so Ganesha doesn't use the parent directory fd, but rather an fd already open on the desired inode.

FSALs other than FSAL_VFS (and FSAL_GPFS which predated FSAL_VFS and the open_by_handle_at and name_to_handle_at system calls, but takes advantage that ANY kernel module can implement the same interface because the underlying exportfs functions MUST be exported in order for the knfsd module to work and FSAL_XFS where XFS has it's own interface to the underlying exportfs functions) use different interfaces to the same functionality of converting an NFS file handle into a reference to a file.

CIFS (Samba) is statefull, and during a session, a file is opened and the Samba process keeps the file descriptor open and has it's own handle mechanism to find that open file descriptor, but that doesn't have to survive the loss of the connection (so if the Samba process terminates, the client recovers some other way). CIFS does have a newer recoverable file handle, I'm not sure how it works, Samba may utilize open_by_handle_at to implement that.

During the process of getting the name_to_handle_at and open_by_handle_at system calls into Linux, it was determined that they should be privileged system calls for security reasons (they can by used to bypass file protections by allowing the caller to "guess" a file handle for a file that is in a directory not accessible by the caller. At a minimum it can be used to "peek" into the directory to see if certain files exist (do you get an ENOENT or some other error), and if proper permissions aren't set on directories or files, allow actual access to the files (note that many NFS v3 servers actually expose this same vulnerability, but at least ONLY on exported filesystems.

So there's a full explanation of what's going on...

**Comment by ffilz** [comment]
Closed as resolved.
