### ISSUE TITLE
NFSV3 lock reclaim failed due to Lock conflict in FSAL_CEPH

### ISSUE THREAD

**Issue by zs0723** [nfs-ganesha/nfs-ganesha#545]
When I try to check NFSv3 client lock reclaim behavior, but client got 'NLM4_DENIED'. The root cause is that : FSAL_CEPH report Lock Conflict when Ganesha try to lock the same file when client sends the lock reclaim request.
In my understanding,  FSAL_CEPH behavior is correct because it need to hold the lock  and report lock conflict  in case of other client got the lock.  So Ganesha should allow Lock conflict if the lock request is a reclaim lock and the lock owner is the same.

But check the code, there is no lock conflict handling logic in ganesha v2.8
```
state_status = state_lock(obj,
				  nlm_owner,
				  nlm_state,
				  arg->block ? STATE_NLM_BLOCKING :
					       STATE_NON_BLOCKING,
				  arg->block ? &pblock_data : NULL,
				  &lock,
				  NULL, /* We don't need conflict info */
				  NULL);
	PTHREAD_RWLOCK_unlock(&obj->state_hdl->state_lock);

	/* We prevented delegations from being granted while trying to acquire
	 * the lock. However, when attempting to get a delegation in the
	 * future existing locks will result in a conflict. Thus, we can
	 * decrement the anonymous operations counter now. */
	(void) atomic_dec_uint32_t(&obj->state_hdl->file.anon_ops);

	if (state_status != STATE_SUCCESS) {
		res->res_nlm4.stat.stat =
				nlm_convert_state_error(state_status);

		if (state_status == STATE_IN_GRACE)
			res->res_nlm4.stat.stat = NLM4_DENIED_GRACE_PERIOD;
	} else {
		res->res_nlm4.stat.stat = NLM4_GRANTED;
	}
	rc = NFS_REQ_OK;
```

logs
```
28/02/2020 10:54:01 : epoch 5e5880bd : plana123.seal.com : ganesha.nfsd-2494[svc_5] nlm4_Lock :NLM :DEBUG :REQUEST PROCESSING: Calling nlm4_Lock svid=3 off=0 len=0 cookie=(4:0x41120000) reclaim=yes
28/02/2020 10:54:24 : epoch 5e5880bd : plana123.seal.com : ganesha.nfsd-2494[svc_5] do_lock_op :STATE :F_DBG :FSAL_lock_op returned STATE_LOCK_CONFLICT
28/02/2020 10:54:24 : epoch 5e5880bd : plana123.seal.com : ganesha.nfsd-2494[svc_5] state_lock :STATE :F_DBG :Conflict in FSAL 
28/02/2020 10:54:24 : epoch 5e5880bd : plana123.seal.com : ganesha.nfsd-2494[svc_5] nlm4_Lock :NLM :DEBUG :REQUEST RESULT: nlm4_Lock NLM4_DENIED
```

**Comment by dang** [comment]
I think CephFS should allow us to reclaim the lock.  It's possible that something is wrong with what we're sending it, and it thinks we're someone else.

**Comment by jtlayton** [comment]
What version of ceph are you using here? (both libcephfs and MDS versions, please)

Only nautilus and above support blowing away state held by a previous client when the server restarts. With an earlier ceph version you could end up issuing a lock request while the MDS still has a session with state from the earlier client session, and see just this result.

**Comment by jtlayton** [comment]
I'll note too here that there is a long delay here between the first and subsequent messages. That suggests that the client in this case is hung waiting for caps that were held by the previous client (which is now dead).

**Comment by zs0723** [comment]
Hi Jeff, I am using Ceph luminous version, libcephfs and MDS share the same version. 
Do you mean that there is no reclaim lock support below nautilus version, right?

**Comment by jtlayton** [comment]
libcephfs itself doesn't support reclaiming locks. When the ceph client (ganesha) is restarted, it creates a new session with the MDS, which then attempts to claim all of the state held by the previous client by establishing new opens and locks. The old client can take a while to time out and get blacklisted however (usually ~60s by default), which can significantly eat into the grace period.

For Nautilus, we added the ability for the new (restarted) client to request that the session held by the previous client be immediately removed, which allows it to get on with the business of reclaiming state for the NFS clients more quickly.

In practice, we don't recommend using ganesha+ceph for any sort of stateful usage with anything prior to nautilus for this reason. It's also recommended to use NFSv4.1 instead of earlier versions as that allows the server to lift the grace period early if all of the clients have finished reclaiming. The use of v3 locking with FSAL_CEPH is largely untested, so YMMV there.

**Comment by zs0723** [comment]
Hi Jeff,  thanks for your well detail explanation, learned a lot.  I will close the issue.
