### ISSUE TITLE
Clean up comments in SAL

### ISSUE THREAD

**Issue by ffilz** [nfs-ganesha/nfs-ganesha#569]
Particularly:

Look for comments about cache_inode

Comment in state_release_grant regarding two threads racing on same cookie (this can't happen, cookie lookup removes from hash table so only one thread can access a cookie via lookup).

**Comment by ffilz** [comment]
Keeping this for the backlog

**Comment by ffilz** [comment]
This is addressed by https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/514191

However, we may want to consider converting the sysadmin visible things (dbus, logging, and config) to mdcache.

@dang @kalebskeithley Any thoughts?

**Comment by dang** [comment]
Config has been handled, sort of.  There's duplicate CACHE_INODE and MDCACHE blocks, and the cache_inode one is deprecated since 2.8.  So we can technically remove it at any time.

Logging we should fix.

DBUS we should also fix, but if we can we should do the duplicate+deprecate thing.  (I don't know if that's possible in DBUS)

**Comment by ffilz** [comment]
New issues opened for the other bits. Closing this as resolved.
