### ISSUE TITLE
Why can't nfs-ganesha cluster and synchronize meta data

### ISSUE THREAD

**Issue by fantastic2085** [nfs-ganesha/nfs-ganesha#586]
Why can't nfs-ganesha cluster and synchronize meta data

**Comment by dang** [comment]
Because it's not a clustered filesystem.  Instead, it is a filesystem translator that runs on top of a clustered filesystem (such as Ceph, Gluster, LizardFS, or GPFS), and translates access into NFS or 9P.  It's up to the actual clustered filesystems to synchronize metadata.

There's no reason in principal why a clustered FS for Ganesha couldn't be written, but with the availability of other clustered filesystems, no one has needed it.

**Comment by ffilz** [comment]
Closing as will not enhance.
