### ISSUE TITLE
Unused variable assignment in code base

### ISSUE THREAD

**Issue by FloridSleeves** [nfs-ganesha/nfs-ganesha#654]
Hi! I've recently used some tool to check nfs-ganesha code (master branch, newest version) and find that there are a lot of unused value assignments in the code base. When a developer assign some value to a variable, the expectation is to use the value somewhere. So these unused definitions could potentially indicate bugs:

1)

In src/FSAL/posix_acls.c, line 661:
` ret = acl_get_permset(d_entry, &d_permset);`

The return value of `acl_get_permset()` is not handled when it’s possibly not 0. So there may need to be:
```
if(ret)
{
	LogWarn(COMPONENT_FSAL, “Cannot retrieve permission set”)
}

```
It’s the same for line 671, line 537, line 552 and line 176.

2) 

The rest of the unused value assignments are as follows. Though I don't know why their value is unused, they could possibly indicate bugs:

File	|Variable	|Line|
|-----|-----------|-------------|
src/Protocols/NFS/nfs4_op_readdir.c	|mem_left	|324|
src/SAL/recovery/recovery_fs.c	|pathpos	|919|
src/Protocols/NFS/nfs3_write.c	|rc	|108|
src/log/log_functions.c	|b_left	|647|
src/log/log_functions.c	|b_left	|601|
src/log/log_functions.c	|b_left	|1507|
src/support/export_mgr.c	|len_ret	|378|
src/support/export_mgr.c	|len_ret	|517|

3)

Some unused assignments are from initialization. Though they are explicitly not harmful, they may waste some performance and deduce the readability of the code.

|File	|Variable	|Line|
|-----|-----------|-------------|
|src/Protocols/NFS/nfs4_Compound.c	|bad_op_state_reason	|754|
|src/support/exports.c	|anon_gid	|3064|
|src/Protocols/NFS/nfs_proto_tools.c	|attribute_to_set	|4515|
|src/FSAL/fsal_helper.c	|note	|192|
|src/FSAL/commonlib.c	|cause	|2496|
|src/FSAL/commonlib.c	|cause	|2561|
|src/FSAL/commonlib.c	|fd	|531|
|src/support/nfs_creds.c	|auth_label	|259|

I will appreciate it so much if you could take a bit time to confirm.

Even if they are not bugs, they may invoke compiler warnings and may still deserve to be dealt with. I wonder if I can help to remove them so that they can keep quiet when compiled.

Thanks!

**Comment by ffilz** [comment]
Please ignore the master branch, or are you looking at next? The active development branch is next and it should be the default branch. In fact the master branch no longer exists.

If you actually see issues in next, feel free to submit a patch via Gerrithub, see src/CONTRIBUTING_HOWTO.txt

**Comment by FloridSleeves** [comment]
Thanks for your reply! Sorry for the typo, it's next branch. For the first and third category, I will submit patch to Gerrithub. But for the second category, I wonder whether it's a bug or not. Could you please take a look at them and confirm?

Thanks!!

**Comment by ffilz** [comment]
For the first one, sure, we should handle the error return case and not silently fail.

For the following from the 2nd group:
Protocols/NFS/nfs4_Compound.c:754	bad_op_state_reason
This one is used, and it's safest to initialize it (and relatively cheap) just in case the place it is used is reached without otherwise being set. Some compilers have been aggressive at thinking a variable can be used uninitialized so something these apparent
extraneous initializations are to calm such a compiler warning.

support/exports.c:3064				anon_gid 
This looks like a tool failure, the line references anon_uid which has been set

Protocols/NFS/nfs_proto_tools.c:4515	attribute_to_set 
That looks like a bug and appears to ignore the first attribute bit set

FSAL/fsal_helper.c:192				note
Another overly cautious initialization that may be flagged as uninitialized by aggressive compiler, and relatively harmless.
	
FSAL/commonlib.c:2496				cause 		
Another overly cautious initialization that may be flagged as uninitialized by aggressive compiler, and relatively harmless.

FSAL/commonlib.c:2561				cause 		
Another overly cautious initialization that may be flagged as uninitialized by aggressive compiler, and relatively harmless.

FSAL/commonlib.c:531**				fd
Code changes may have changed how this is used, it looks like it doesn't need to be initialized anymore (and in fact, if set from first_fd should be done with dup).

support/nfs_creds.c:259				auth_label 	
Another overly cautious initialization that may be flagged as uninitialized by aggressive compiler, and relatively harmless.

For the following from the 3rd group:
Protocols/NFS/nfs4_op_readdir.c:324	mem_left
Can be removed, there is already a check of mem_left and mem_left isn't further used.

SAL/recovery/recovery_fs.c:919		pathpos
Yea, remove this one also.

Protocols/NFS/nfs3_write.c:108		rc
Yea, no need to initialize rc here.
	
log/log_functions.c:647				b_left	
log/log_functions.c:601				b_left
log/log_functions.c:1507				b_left
With these, the convention is to always compute b_left even if it is ignored. It makes it safer if someone adds more display calls to the chain, but I suppose it wouldn't be awful in these cases where b_left won't be used to invoke the display function as (void) dispay.... It is allowed to ignore the return of a display function since it has safely constructed the display buffer, continuing to append to a full buffer doesn't blow the buffer and is resolved quickly (sprintf for example won't be invoked by display_printf if the buffer is already full).

support/export_mgr.c:378			len_ret 		
support/export_mgr.c:517			len_ret 
These are false positive, len_ret is used.

**Comment by FloridSleeves** [comment]
Thank you a lot for your patient confirmation! Will submit patches to Gerrihub according to your guidance :-)

But for the support/export_mgr.c:378, unused definition of len_ret, I check it again and still feel it’s an unused definition: in line 380, the break statement will jump out of the loop to line 423 and then return. So the value assigned to len_ret in line 378 is not used. I’m not quite sure whether it’s a bug or not.

**Comment by ffilz** [comment]
> support/export_mgr.c:378

Oh, right, yes, that instance can be removed.

**Comment by ffilz** [comment]
BTW, for all the simple removals, you can put them in a single patch.

**Comment by FloridSleeves** [comment]
Sure!

**Comment by FloridSleeves** [comment]
Hope you have a great Thanksgiving day!

I have submitted the patch to gerrihub: 
https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/506690
https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/506689
https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/506714 (this is correcting some syntax error that I make)

If there is any problem, please do not hesitate to tell me.
Thanks!

**Comment by ffilz** [comment]
Closing as resolved.
