### ISSUE TITLE
[Question/Information] ZFS configuration.

### ISSUE THREAD

**Issue by blmhemu** [nfs-ganesha/nfs-ganesha#663]
Can someone provide a very simple ZFS configuration ?
I have followed the wiki : https://github.com/nfs-ganesha/nfs-ganesha/wiki/ZFS but was unable to succeed.

**Comment by dang** [comment]
I'm not sure if any of us have ever used Ganesha on ZFS.  It *should* just be the normal FSAL_VFS example, I believe.  However, you might get a wider audience if you ask on the mailing list (devel@lists.nfs-ganesha.org)

**Comment by blmhemu** [comment]
Hey @dang thanks for reaching out. I have some success using FSAL_VFS. But the concern is about "what if zfs has not mounted that path yet ?" Also it seems strange that there appears to be no code with the term "zfs" in the whole repo other than a few mentions in docs and changelogs.

![image](https://user-images.githubusercontent.com/19410501/100896375-8eecbf00-34e4-11eb-98c7-9bcbf7e04cbd.png)
This is what i mean ...

**Comment by ffilz** [comment]
There used to be a FSAL_ZFS, it was removed partly due to lack of support. No one actively working on Ganesha is really in a position to support use of ZFS file systems. In theory they can be exported with FSAL_VFS though perhaps some functionality is lost compared to what might be possible with a ZFS specific FSAL.

You could try reaching out on the support or devel mailing lists and maybe someone else out there is using ZFS.

The beauty of open source is anyone can contribute something. The downside is that if the original contributor goes away and the active community is not interested or not able to support the contribution, it can bitrot and become useless and may be removed as unsupportable. That is what happened to FSAL_ZFS, in fact, due to FSAL API changes, the old FSAL_ZFS was unusable and the active community didn't have the knowledge or resource to fix up FSAL_ZFS to the new API.

I have marked the ZFS page to indicate it is no longer supported, and removed it from the table of contents.
