### ISSUE TITLE
mdcache_lru can't reuse the entry  and out of memory

### ISSUE THREAD

**Issue by agin719** [nfs-ganesha/nfs-ganesha#664]
hello，I implemented a FSAL with ganesha. But I meet a problem. I observed In MDCache level with gdb, my lru_state is like that :

(gdb) p lru_state
$1 = {entries_hiwat = 100000, entries_used = 490828, chunks_hiwat = 100000, 
  chunks_used = 3836, fds_system_imposed = 1048576, fds_hard_limit = 1038090, 
  fds_hiwat = 943718, fds_lowat = 524288, futility = 0, per_lane_work = 50, 
  biggest_window = 419430, prev_fd_count = 0, prev_time = 1607066035, fd_state = 0}

the variable entries_used  is continue to grow up,  many entries has benn created,  which makes OOM.  But I use FSAL_VFS, the entries_used is less than or equal to the entries_hiwat, so the chunks_used. 

I learn the code of ganesha, known that when entries_used >= entries_hiwat, the the function mdcache_lru_get will get the entry from LRU,  the trace is ： 
mdcache_new_entry ---> mdcache_lru_get ---> lru_try_reap_entry --> lru_reap_impl 
but in lru_reap_impl , all the entry->lru->refcnt != 2, which makes mdcache_lru_get can't get the entry from LRU and alloc a 
 new entry.
So my question is, In FSAL Level, What factors will affect the  entry->lru->refcnt ??  or what make the entry->lru->refcnt != 2 and can't  reuse the entry in LRU.

Thank you!

**Comment by dang** [comment]
The refcount on an entry is a count of the number of times it's used by the upper layer of Ganesha or by MDCACHE.  These uses involve having a pointer to the entry, so the entry must not be freed while anyone has a pointer to it, or Ganesha will crash when that pointer is used.  MDCACHE maintains one special refcount, called the "sentinel refcount" that represents it's entry in the hash table, so an entry's refcount will always be at least one.  When we're trying to reap, we take a refcount, since we have a pointer, and so an unused entry will have a refcount of 2, which is where that comes from.

A FSAL shouldn't be able to influence the refcount of an entry, that's all above the level of the FSAL.  However, somehow it clearly is.  If you know how to use LTTng, you can turn on the mdc_lru_ref and mdc_lru_unref tracepoints, and see where refcounts are happening.  Otherwise, you can add log lines at those points.  This will list the function and line-number of the code that's taking a ref.  That might help.

Beyond that, it's hard to know without being able to see the code in question.

**Comment by agin719** [comment]
I test FSAL_MEM and FSAL_VFS, and I found FSAL_MEM has the same problem.  
my step is:
1、modify Entries_HWMark and Chunks_HWMark to 1000
# vi mdcache_read_conf.c 
        CONF_ITEM_UI32("Entries_HWMark", 1, UINT32_MAX, 1000,
                       mdcache_parameter, entries_hwmark),
        CONF_ITEM_UI32("Chunks_HWMark", 1, UINT32_MAX, 1000,
                       mdcache_parameter, chunks_hwmark),

2、mount the MEM
3、write about 10000 file.
4、observe the lru_state.
(gdb) p lru_state
$6 = {entries_hiwat = 1000, entries_used = 11657, chunks_hiwat = 1000, chunks_used = 402, 
  fds_system_imposed = 1048576, fds_hard_limit = 1038090, fds_hiwat = 943718, 
  fds_lowat = 524288, futility = 0, per_lane_work = 50, biggest_window = 419430, 
  prev_fd_count = 0, prev_time = 1607347734, fd_state = 0}

My nfs-ganesha version is 3.3.

**Comment by agin719** [comment]
I test FSAL_MEM and FSAL_VFS, and I found FSAL_MEM has the same problem.
my step is:
1、modify Entries_HWMark and Chunks_HWMark to 1000
vi mdcache_read_conf.c
    CONF_ITEM_UI32("Entries_HWMark", 1, UINT32_MAX, 1000,
                   mdcache_parameter, entries_hwmark),
    CONF_ITEM_UI32("Chunks_HWMark", 1, UINT32_MAX, 1000,
                   mdcache_parameter, chunks_hwmark),
2、mount the MEM
3、write about 10000 file.
4、observe the lru_state.
(gdb) p lru_state
$6 = {entries_hiwat = 1000, entries_used = 11657, chunks_hiwat = 1000, chunks_used = 402,
fds_system_imposed = 1048576, fds_hard_limit = 1038090, fds_hiwat = 943718,
fds_lowat = 524288, futility = 0, per_lane_work = 50, biggest_window = 419430,
prev_fd_count = 0, prev_time = 1607347734, fd_state = 0}

My nfs-ganesha version is 3.3.

**Comment by agin719** [comment]
> I test FSAL_MEM and FSAL_VFS, and I found FSAL_MEM has the same problem.
> my step is:
> 1、modify Entries_HWMark and Chunks_HWMark to 1000
> vi mdcache_read_conf.c
> CONF_ITEM_UI32("Entries_HWMark", 1, UINT32_MAX, 1000,
> mdcache_parameter, entries_hwmark),
> CONF_ITEM_UI32("Chunks_HWMark", 1, UINT32_MAX, 1000,
> mdcache_parameter, chunks_hwmark),
> 2、mount the MEM
> 3、write about 10000 file.
> 4、observe the lru_state.
> (gdb) p lru_state
> $6 = {entries_hiwat = 1000, entries_used = 11657, chunks_hiwat = 1000, chunks_used = 402,
> fds_system_imposed = 1048576, fds_hard_limit = 1038090, fds_hiwat = 943718,
> fds_lowat = 524288, futility = 0, per_lane_work = 50, biggest_window = 419430,
> prev_fd_count = 0, prev_time = 1607347734, fd_state = 0}
> 
> My nfs-ganesha version is 3.3.

I  have a idea of the reason, the entry that can't be reused is created by chunk cache. After chunks_used>=chunks_hiwat, these entries will be release and the refcnt = 1. When I turn off the chunk cache, (set Dir_Chunk = 0), entries can be reused normally. Is my understanding correct?

And I have another question: is the whence of chunk cache consistent with in FSAL? In my custom fsal layer,  the whence is not increating linearly,  I Observe that if the number of files in a directory is greater than chunk_ hiwat * Dir_Chunk,  the whence became incorrect in FSAL, What are the rules of the variable "fsal_cookie_t Whence"?

**Comment by dang** [comment]
Do you have whence_is_name set in your fsal's fs_info?  This changes readdir and it's use of whence dramatically.

By default, whence behaves the same way as POSIX readdir.  That is, whence for a dirent is the lookup key for the next dirent in the directory listing.  So if, for example, my FSAL stores dirents in an array, and uses the index for whence, it would look like this:

dirent          whence

a                 1
b                 2
c                 3
d                 4
e                0xffffffff

So whence for a (the first dirent) is the "address" of b, which is the second dirent, and so on.  The whence for the last one is the highest possible whence.  This means we just return the last whence as a cookie to the client, and when the client continues the readdir, it will automatically be looking up the next dirent in the listing.


If whence_is_name is set, then it behaves differently.  In this case, whence is the key of the the *current* dirent.  So the same dir listing would be:

a          0
b          1
c          2
d          3
e          4

This setup was designed for FSAL_RGW, which doesn't have a filesystem, but sits on top of an S3-compatible object store.  There's no listing equivalent in that setup to POSIX readdir whence.  In this case, we return the last whence to the client, but when we get it back, we have to skip one before we continue.  It's further complicated by the fact that whence is a string in this case, so we need to keep a mapping of the strings to uint64 that we can return to the client.

The takeaway from this is that you should not use whence-is-name unless you have to.  FSAL_MEM has the ability to use it, so that we can test it without a Ceph cluster, but FSAL_MEM is just for testing anyway.

**Comment by agin719** [comment]
> Do you have whence_is_name set in your fsal's fs_info? This changes readdir and it's use of whence dramatically.
> 
> By default, whence behaves the same way as POSIX readdir. That is, whence for a dirent is the lookup key for the next dirent in the directory listing. So if, for example, my FSAL stores dirents in an array, and uses the index for whence, it would look like this:
> 
> dirent whence
> 
> a 1
> b 2
> c 3
> d 4
> e 0xffffffff
> 
> So whence for a (the first dirent) is the "address" of b, which is the second dirent, and so on. The whence for the last one is the highest possible whence. This means we just return the last whence as a cookie to the client, and when the client continues the readdir, it will automatically be looking up the next dirent in the listing.
> 
> If whence_is_name is set, then it behaves differently. In this case, whence is the key of the the _current_ dirent. So the same dir listing would be:
> 
> a 0
> b 1
> c 2
> d 3
> e 4
> 
> This setup was designed for FSAL_RGW, which doesn't have a filesystem, but sits on top of an S3-compatible object store. There's no listing equivalent in that setup to POSIX readdir whence. In this case, we return the last whence to the client, but when we get it back, we have to skip one before we continue. It's further complicated by the fact that whence is a string in this case, so we need to keep a mapping of the strings to uint64 that we can return to the client.
> 
> The takeaway from this is that you should not use whence-is-name unless you have to. FSAL_MEM has the ability to use it, so that we can test it without a Ceph cluster, but FSAL_MEM is just for testing anyway.

Thank you for your answer, I didn't set the whence_is_name, but my whence is like that:
 a   0x100000000001
 b  0x1000ffffffff
 c   0x200000000001
 d  0x2000ffffffff
 e   0x3000ffffffff

the high bit of whence represent the subdir of my file organization.   this makes the chunk cache can't not work properly, right?

**Comment by dang** [comment]
No, if you don't have whence_is_name set, we make no assumptions at all about the contents of whence.  We don't care about ordering or anything.  Any whence at all should be fine.

**Comment by agin719** [comment]
> No, if you don't have whence_is_name set, we make no assumptions at all about the contents of whence. We don't care about ordering or anything. Any whence at all should be fine.

OK, thank you very much!
