### ISSUE TITLE
non-free file(s) / please clarify license

### ISSUE THREAD

**Issue by onlyjob** [nfs-ganesha/nfs-ganesha#69]
`src/FSAL/FSAL_PT/fsal_attrs.c` contains

    Copyright IBM Corp. 2012, 2012
    All Rights Reserved

which indicates non-free file: please remove it or clarify its licensing terms with IBM.
Thanks.

**Comment by onlyjob** [comment]
Same issue affects

    src/FSAL/FSAL_PT/fsal_close_listener.c
    src/FSAL/FSAL_PT/fsal_convert.c
    src/FSAL/FSAL_PT/fsal_create.c
    src/FSAL/FSAL_PT/fsi_ipc_ccl.h
    src/FSAL/FSAL_PT/pt_ganesha.c
    src/FSAL/FSAL_PT/pt_ganesha.h
    src/FSAL/FSAL_PT/pt_util_cache.h

**Comment by onlyjob** [comment]
And `src/Protocols/XDR/nfs4.x`:

~~~~
Copyright (C) The Internet Society (1998-2003)
All Rights Reserved.
~~~~

**Comment by onlyjob** [comment]
Also file `src/tools/maketest` contains only `Copyright CEA/DAM/DIF  (2008)` without mentioning any license...

**Comment by onlyjob** [comment]
Similar problem affects file `src/libntirpc/src/auth_time.c`.
Reported as https://github.com/linuxbox2/ntirpc/issues/2

**Comment by joejulian** [comment]
+1

**Comment by ffilz** [comment]
I cleaned up a bunch of license issues, but please take discussion of any remaining issues to the nfs-ganesha-devel sourceforge e-mail list.

**Comment by onlyjob** [comment]
Thanks.

I had a quick look at _2.3-rc5_ and found
"Copyright CEA/DAM/DIF  (2008)" in `./src/tools/maketest`.

---

in `src/FSAL/FSAL_PT` at least the following files 

    fsal_convert.c
    pt_ganesha.h
    pt_util_cache.h
    fsal_create.c
    pt_ganesha.c
    fsal_close_listener.c
    fsi_ipc_ccl.h
    fsal_attrs.c

are still problematic due to "Copyright IBM Corp. 2012, 2012 All Rights Reserved" (no license); 

---

Also there is a spelling error ("Free Software F oundation" instead of "Free Software Foundation") in license grant of the following files:

    src/SAL/nfs4_clientid.c

`./src/Protocols/XDR/nfs4.x` is "Copyright (C) The Internet Society (1998-2003). All Rights Reserved." (no license).

---

Remaining _BSD-4-Clause_ files:

    src/os/freebsd/mntent_compat.c

---

As far as I can tell only `src/libntirpc/src/crypt_client.c` and non-free RFCs were removed from `share/doc/RFC` which is good but there are still many problematic files and minor problems like version-less CDDL license grants etc...

I have no time to follow Ganesha mail list. Developers should monitor bug reports and ideally respond promptly.

**Comment by onlyjob** [comment]
There is a typo "Lessor" instead of "Lesser" in `src/scripts/ganeshactl/Ganesha/admin.py`;

Header of `src/scripts/ganeshactl/Ganesha/ganesha_mgr_utils.py` (_GPL-2+_) seems to be outdated because all surrounding files were recently changed from _GPL-2+_ to _LGPL-3+_... However during license update of all those files in `ganeshactl` nobody touched disclaimer which still refer to GPL instead of LGPL...

**Comment by lieb** [comment]
On Friday, October 02, 2015 07:26:21 PM Dmitry Smirnov wrote:
> There is a typo "Lessor" instead of "Lesser" in
> `src/scripts/ganeshactl/Ganesha/admin.py`;
> 
> Header of `src/scripts/ganeshactl/Ganesha/ganesha_mgr_utils.py` (_GPL-2+_)
> seems to be outdated because all surrounding files were recently changed
> from _GPL-2+_ to _LGPL-3+_... However during license update of all those
> files in `ganeshactl` nobody touched disclaimer which still refer to GPL
> instead of LGPL...
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/nfs-ganesha/nfs-ganesha/issues/69#issuecomment-145194466

Those files that contain the main, as this one does do not have LGPL which 
makes sense for libraries and other files linked to.  I left this alone because 
I was not the author.

Jim
-- 
Jim Lieb

Mobile: 831-295-9317

"If ease of use was the only requirement, we would all be riding tricycles"
- Douglas Engelbart 1925–2013

**Comment by onlyjob** [comment]
As far as I'm concerned the biggest licensing problem in Ganesha is non-free files in [libntirpc](https://github.com/nfs-ganesha/ntirpc), namely https://github.com/linuxbox2/ntirpc/issues/2 and https://github.com/linuxbox2/ntirpc/issues/1. In turn those files were inherited from original "libTirpc".

Ganesha's Ntirpc is a fork of [Linuxbox2 Ntirpc](https://github.com/linuxbox2/ntirpc) where the non-free files were inherited from. It it not possible to report bugs to Ganesha's Ntirpc (bug tracker is disabled).

It is not possible to build Ganesha without non-free files from "linNtirpc" hence Ganesha is not suitable for Debian due to lack of DFSG compliance. :(

**Comment by ffilz** [comment]
libntrirpc is a separate project. Since Ganesha uses it, it is important that we have it's licensing correct, however, an nfs-ganesha github issue is absolutely the wrong place to address libntirpc issues.

The FSAL_PT files are for an IBM proprietary filesystem and can safely be dropped from anyone else's distribution. They are present in this repo because we encourage FSALs to be in-tree where we can see what dependencies they have. I have asked they update their files, however, in the meantime, for packaging in distros like Debian and Red Hat, the best thing to do is not include them in your source packaging,

src/os/freebsd/mntent_compat.c: this file is only necessary for freebsd builds and can safely be removed from Linux distributions. It may even be safe anyway since it will NEVER be built into a Ganesha binary for Linux.

**Comment by ffilz** [comment]
Ok, I think I can correct some of the issues:

src/Protocols/XDR/nfs4.x (and other .x files, looking at RFC 7531, I see that the nfs4.x file has something similar to a 3-clause BSD license. I will get this license into the files.

There is a typo "Lessor" instead of "Lesser" in src/scripts/ganeshactl/Ganesha/admin.py: easy to fix
Header of src/scripts/ganeshactl/Ganesha/ganesha_mgr_utils.py (GPL-2+) seems to be outdated because all surrounding files were recently changed from GPL-2+ to LGPL-3+... However during license update of all those files in ganeshactl nobody touched disclaimer which still refer to GPL instead of LGPL... I think we can easily fix this.

"Copyright CEA/DAM/DIF (2008)" in ./src/tools/maketest. I'll have a look at this one

**Comment by ffilz** [comment]
As far as following bug reports...

github issue tracker is flawed, most of our developers do not see the issues and we can't assign them to people. This makes it highly unlikely the issues will be addressed. The only sure way to make sure the developers see the issues is to use our mailing list.

However, failing that, issuing bugs to the Red Hat hosted bugzilla has a somewhat higher likelyhood of being followed and we CAN assign bugs to the right people.

https://bugzilla.redhat.com/enter_bug.cgi?product=nfs-ganesha

**Comment by phdeniel** [comment]
On 10/05/15 05:40, Frank Filz wrote:
>
> "Copyright CEA/DAM/DIF (2008)" in ./src/tools/maketest. I'll have a 
> look at this one
>
Actually, src/tools/maketest can be removed for its pretty deprecated. 
Tests for Ganesha are a separate project (Sigmund, hosted on SF.net as a 
LGPL project, but it depends on many other tests suites).

     Philippe

**Comment by mattbenjamin** [comment]
onlyjob:  can you enumerate the set of files in libntirpc which you believe to be non-free?

**Comment by onlyjob** [comment]
Sorry for delay. I've checked latest release tarball 1.3.1 and I'm concerned about the following files:

`ntirpc/getpeereid.h`,
`src/getpeereid.c`: "Portions Copyright (c) 1996-2012, PostgreSQL Global Development Group", no license;

`ntirpc/rpc/clnt_stat.h`: "Copyright (c) 1986 - 1991, 1994, 1996, 1997 by Sun Microsystems, Inc. All rights reserved.", no license;

`man/*`: "Copyright 1989 AT&T; 1988 Sun Microsystems, Inc. - All Rights Reserved.", no license.

Also it would be nice to declare overall BSD-3-Clause license for the whole _linbtirpc_ more prominently. File `COPYING` only mention "Copyright (c) Bull S.A.  2005" who is unlikely a main copyright holder.

**Comment by onlyjob** [comment]
File `ntirpc/rpc/clnt_stat.h` is a most important one to clarify its license.

**Comment by ffilz** [comment]
At this point, perhaps this issue should be opened against linuxbox2/libntirpc project instead of Ganesha project since we can do nothing inside Ganesha project.

**Comment by onlyjob** [comment]
https://github.com/linuxbox2/ntirpc/issues/2

**Comment by ffilz** [comment]
Ok, closing this since issue is opened in linuxbox2, Ganesha will pick up any updates that are made.
