### ISSUE TITLE
"Documentation" section in README is empty

### ISSUE THREAD

**Issue by werdnum** [nfs-ganesha/nfs-ganesha#698]
You could at least link, say, [here](https://manpages.ubuntu.com/manpages/bionic/man8/ganesha-config.8.html) if you don't have anywhere better to link to.

**Comment by ffilz** [comment]
Which README? Is this an Ubuntu specific question?

**Comment by werdnum** [comment]
This page https://github.com/nfs-ganesha/nfs-ganesha/wiki#Documentation

**Comment by ffilz** [comment]
I wouldn't want to point to some downstream documentation that may be out of date with the current supported versions.

This works but would be the latest development branch documentation:

https://github.com/nfs-ganesha/nfs-ganesha/blob/next/src/doc/man/ganesha-config.rst

We could point to that document for the various supported versions.

Or we could point to the directory since the linking between man pages doesn't seem to work

Anyone else have any thoughts?

**Comment by ffilz** [comment]
We should clean up the wiki page...

**Comment by ffilz** [comment]
Done, added links to next and V3-stable (will update to V4-stable once that's available.
