### ISSUE TITLE
Bother how to forbid to mount the root directory.

### ISSUE THREAD

**Issue by lpstudy** [nfs-ganesha/nfs-ganesha#704]
We have tries the sub directory mount mode. That is, we use the following command to mount one sub directory (ie. **dir1**) of the filesystem to **/mnt/nfs**.
```
ALLOW:    mount -t nfs4 -o minorversion=1,port=8800,noac SERVER_IP:/dir1   /mnt/nfs
```

In this case, one sub direcotry will server one user. Different users use different sub directories. And we want to forbit to mount the root direcotry of the file system. I do not know how to achieve this.
```
FORBID:    mount -t nfs4 -o minorversion=1,port=8800,noac SERVER_IP:/   /mnt/nfs
```

**Comment by ffilz** [comment]
How are your users distinguished? Are they different clients, or just different user credentials (if so, what security flavor do you use)?

If the users are different clients, you could have an export per user with a CLIENT block limiting access.

If the users are distinguished primarily by different credentials, the best you can do is set up permissions for each directory.

For NFSv4, the client MUST be able to access the directories between / and the mount because the client doesn't actually mount the directory specified. It mounts / and then navigates to the directory of interest.

Also usually for NFSv4, the export path "/" is the root of the pseudo file system and is not backed by any real file system, and is a read only memory filesystem.

**Comment by ffilz** [comment]
I think this is beyond the scope of Ganesha and is more a general NFS server management question. Closing.
