### ISSUE TITLE
low timestamp granularity support in nfs-ganesha

### ISSUE THREAD

**Issue by skmprabhu1** [nfs-ganesha/nfs-ganesha#741]
Currently,  timestamp granularity is hard coded with 1sec in ganesha.  

And, sometimes nfs client shows below warning.
“WARNING: This NFS server only supports 1-second timestamp granularity"

As the per discussion(in call),  timestamp granularity  should be based on the underlying filesystem support. 
We need to add new fsal api to get timestamp granularity from FSAL and use it.

**Comment by ffilz** [comment]
Part 1 of this is https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/523214

However, to make any difference, the FSALs need to set something other than 1 second...

The issue is what actually to set.

FSAL_PROXY_V3 requests time_delta from the server, however, this may not be ideal. The Limux NFSv3 server ALSO reports a 1 second time_delta...

For FSAL_VFS (and most likely FSAL_GPFS, FSAL_CEPH, and FSAL_GLUSTER), while most filesystems seem to support nanosecond resolution in time stamps (I verified setting such in xfs, ext4, and btrfs) the reality is the time functions may not have this resolution. The Linux NFSv4 server sets time_delta to a time resolution from the super block (which often is 1 ns) or NSEC_PER_SEC / HZ whichever is greater. Since HZ is typically 1024, that's effectively 1ms resolution.

I'm trying to decide what each FSAL should report considering there's not really a clear way of reliably getting the actual value.

It would help to understand what client is issuing this warning, and what behavior change that causes and what trigger value it uses.

Perhaps we could just set 1ms resolution which is probably close enough to the worst granularity we would actually see.

But if a client really is trying to do something smart with time_delta, maybe we should strive to be accurate in some way.

**Comment by ffilz** [comment]
BTW, I did a test of touching files on xfs, ext4. and btrfs, and the timestamps are NOT rounded as far as I can tell, I see odd numbers of nsec if I do:

[root@fedora src]# touch /export/btrfs/tcheck /export/test1/tcheck /export/xfs1/tcheck && ls -l  --time-style=full-iso /export/xfs1/tcheck /export/test1/tcheck /export/btrfs/tcheck
-rw-r--r--. 1 root root 0 2021-09-01 16:48:18.838843299 -0700 /export/btrfs/tcheck
-rw-r--r--. 1 root root 0 2021-09-01 16:48:18.838843299 -0700 /export/test1/tcheck
-rw-r--r--. 1 root root 0 2021-09-01 16:48:18.838843299 -0700 /export/xfs1/tcheck

**Comment by ffilz** [comment]
There are two patches for this:

https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/523214
https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/523405

Failing to find any good way to programatically get a value, and after some discussion, I have set time_delta to 100 ns for each FSAL. I'm not sure this is the best value. Ultimately, I think every FSAL (including FSAL_VFS with common filesystems) stores timestamps to 1 ns granularity however, it seems unlikely the filesystems actually  would ever produce two timestamps 1 ns apart. On the other hand, as noted above, I have seen odd number of ns which means they aren't rounded by either a power of 10 or a power of 2. Note also that touch might produce a different granularity of time than the kernel updating mtime or ctime as a result of an actual file change.
