### ISSUE TITLE
Why setattr twice for each open ?

### ISSUE THREAD

**Issue by liyinshubyte** [nfs-ganesha/nfs-ganesha#746]
@ffilz When ganesha create file by OP_OPEN, ganesha will call [setattr](https://github.com/nfs-ganesha/nfs-ganesha/blob/next/src/FSAL/FSAL_CEPH/handle.c#L1570) after create file in OP_OPEN. But nfs client will also call [OP_SETATTR](https://github.com/torvalds/linux/blob/master/fs/nfs/nfs4proc.c#L3187) after OP_OPEN. So, why we setattr twice ? Because it will increase the latency, so I want to improve it.

**Comment by ffilz** [comment]
Most open/create come with at least some attributes to set. Ganesha is just setting those attributes as requested. Then the compound may come with additional attributes to set, which ganesha is also obligated to set.

What is most likely in this scenario is that it is an EXCLUSIVE create, which needs to set a verifier as part of the open, and then if the exclusive create succeeds, the client wants to set the attributes (usually mtime and ctime) used for the exclusive create verifier to a sensible value. There's no way around this double setting of attributes.

**Comment by liyinshubyte** [comment]
@ffilz Thanks for the explanation. As you said, when EXCLUSIVE create, client send OP_OPEN which need to set verifier, i.e. atime, ctime, mtime, then client send OP_SETATTR which set mode. So can we cache atime, ctime, mtime in ganesha, and when ganesha receives OP_SETATTR, ganesha send one rpc to set atime, ctime, mtime and mode together, which can save one rpc call ? Because in our case, there is a lot of very small file, the time of create file does matter.

**Comment by dang** [comment]
Not if we want to be correct.  The issue is that the client doesn't have to send a SETATTR at all, but we have to set the attributes that were part of the open.

**Comment by liyinshubyte** [comment]
@dang Hi, thanks the explanation.  But client does send SETATTR  [here](https://github.com/torvalds/linux/blob/master/fs/nfs/nfs4proc.c#L3187). Even though the client crash before sending SETATTR, it also seems does not matter. Because, when client crash without sending the SETATTR, the file will not has mode, then the atime, ctime, mtime seems unnecessary for the file without mode.

**Comment by boulos** [comment]
Hmm. Is there a good reason the client doesn't issue this as a COMPOUND of
open exclusive plus setattr?

**Comment by ffilz** [comment]
I just did a test, and I don't see a 2nd SETATTR from the client (Fedora 34) using NFS v4.2.

Ganesha DOES need to do a setattr to the back end to put the exclusive create verifier into mtime/ctime.

Also, mode should be set by the open, and the client for sure sends a mode (the only attribute it sends with the OPEN).

I suspect the client doesn't bother sending a SETATTR for the time because it expects it to change as soon as the application actually writes to the file.

Also, the client CAN'T send the SETATTR in the same compound as the OPEN. That would break the exclusive create verifier which has to remain on the file in case the client doesn't get the response and retries the create.

**Comment by liyinshubyte** [comment]
>  I don't see a 2nd SETATTR from the client (Fedora 34) using NFS v4.2.

@ffilz Hi, following is my test, OPEN followed with SETATTR when touch a file, from the client Debian 4.14.81 using NFS v4.2. 
![image](https://user-images.githubusercontent.com/92144382/136876968-0ca6f149-7eda-4a8c-95d4-8a0b5002f778.png).

The log as follows:

```
    LogCrit(COMPONENT_NFS_V4, "Request: index %d opcode %d is %s version %d",
        data->oppos, data->opcode, data->opname, data->minorversion);

```

**Comment by ffilz** [comment]
That SETATTR is the SETATTR required by the RFC after an exclusive create.

What FSAL are you using? A FSAL COULD avoid extraneous SETATTR by doing the following for V4.1+ with some additional help from Ganesha:

The EXCLUSIVE4_1 create allows setting any attribute on OPEN not used to store the verifier
FATTR4_SUPPATTR_EXCLCREAT specified the attributes that can be set (and thus are not used by the verifier)
A FSAL backend could possibly set attributes atomically and in a single backend request with the open/create (for example PROXY_V4 since it used 4.1 could do so to a compliant proxied server)
We can add plumbing so Ganesha can query the FSAL for the attributes used to store the verifier so if the backend had a way to store the verifier without using one of the V4 required attributes then it could communicate that to the client

If all of this were done, the client would not need to send the separate SETATTR and the FSAL and backend would store the requested attributes from the OPEN PLUS the verifier in a single request

Otherwise, you are observing Ganesha working as expected and in compliance with the RFC

**Comment by liyinshubyte** [comment]
@ffilz Thanks the reply.

> What FSAL are you using?

We use FSAL implemented by ourselves.

> FATTR4_SUPPATTR_EXCLCREAT specified the attributes that can be set (and thus are not used by the verifier)

Is there an existing example of how to use FATTR4_SUPPATTR_EXCLCREAT ? i.e. when and where to set the attributes in FATTR4_SUPPATTR_EXCLCREAT, and how to send it to client ?

**Comment by ffilz** [comment]
No example, actually we will have to add a call to FSAL API to fetch the attribute mask and then plumb up the protocol layer to pass it.

**Comment by liyinshubyte** [comment]
> No example, actually we will have to add a call to FSAL API to fetch the attribute mask and then plumb up the protocol layer to pass it.

@ffilz Do you mean ganesha will add this feature in future ?

> I just did a test, and I don't see a 2nd SETATTR from the client (Fedora 34) using NFS v4.2.

If ganesha has not implemented this feature, why you did not see  a 2nd SETATTR ? sorry for this question.

**Comment by ffilz** [comment]
> 
> 
> > No example, actually we will have to add a call to FSAL API to fetch the attribute mask and then plumb up the protocol layer to pass it.
> 
> @ffilz Do you mean ganesha will add this feature in future ?

We can log this as an enhancement request. I'm not sure when we would get to it unless we have a compelling reason, perhaps someone working on FSAL_PROXY_V4 might find reason to implement this enhancement.

> > I just did a test, and I don't see a 2nd SETATTR from the client (Fedora 34) using NFS v4.2.
> 
> If ganesha has not implemented this feature, why you did not see a 2nd SETATTR ? sorry for this question.

I'm not sure yet, I'm debugging. Somehow we're signalling the client wrong, or there's actually a client bug.
