### ISSUE TITLE
Is FUSE not supported in the latest versions of ganesha?

### ISSUE THREAD

**Issue by Andresnotch** [nfs-ganesha/nfs-ganesha#759]
I noticed there is no longer a folder for FUSE in the newer versions of nfs-ganesha. Does this mean it is not supported anymore? Or maybe there is a better way to use FUSE with ganesha that I missed. What I am trying to do is to create my own implementation of a file system using FUSE, and exporting it with ganesha. Another option I'm looking at is using VFS, but my principal concern is that I don't want my fs to be in the kernel, instead I want it to be in userspace, that's why my first option was FUSE. I appreciate a lot any help that you can provide.

**Comment by ffilz** [comment]
FSAL_FUSE was never that great a solution. If you are developing a new file system in user space, the best option is actually a custom FSAL for that file system which avoids going through multiple semantic translations by going through FUSE or even a kernel file system driver accessed with FSAL_VFS.

**Comment by Andresnotch** [comment]
> FSAL_FUSE was never that great a solution. If you are developing a new file system in user space, the best option is actually a custom FSAL for that file system which avoids going through multiple semantic translations by going through FUSE or even a kernel file system driver accessed with FSAL_VFS.

Sounds great! Thank you for helping me. Just to be sure, there is no longer support for FUSE, and I should look how to create a FSAL of my own or write a VFS to solve this problem. Did I get that correctly?

I might be abusing of your kindness, but do you know where should I start looking to take any of the paths you pointed out?

**Comment by ffilz** [comment]
I'm not sure how it works but it's possible you might be able to FUSE mount your file system and export it with FSAL_VFS. I was looking at something else and noted that quite some time ago I had found the FSAL_VFS handle size for FUSE which implies it works with name_to_handle_at and open_by_handle_at, the operations critical for FSAL_VFS to work with a file system.

That said, it would almost certainly be better to write a FSAL specific to your file system in which case you can completely avoid the kernel. You file system would need to be accessible via a library interface. You can look at FSAL_CEPH and FSAL_GLUSTER as some examples of FSALs that work with user space file systems. Also look at src/include/fsal.h, src/include/fsal_api.h, and src/include/fsal_types.h for lots of description of the FSAL interface.

If you can describe a bit about your file system I can offer some suggestions.

One thing you absolutely need is the ability to generate a "handle" for a file that is at most 59 bytes that can be used to access the file for getattr/stat, read, write., open, byte range locking, readdir, etc. For directories, you will need to have a cookie for each dirent that can be used to find the next dirent in the directory (there is also the possibility if your directories have a persistent order such that the name of the previous entry can be used to find the next entry).

**Comment by Andresnotch** [comment]
This advice has been gold for me. The situation I'm facing is that I do have several functions that allow me to access my FS, and another teammate is building this library so I am able to use those functions outside of the program. I think your second suggestion might be just what I was looking for, and the other FSAL's will surely help me out in figuring out the implementation. So thank you again for helping out, I will let you know if my project was a success!

**Comment by ffilz** [comment]
We can leave this issue open if you like to land further questions as you work through building a FSAL, or you can open new issues, or we can close this and re-open as necessary.

**Comment by apeters1971** [comment]
I am running GANESHA on top of FUSE and the (only) issue there is, that in your code you only change the effective filesystem ID when you obtain a filehandle. The result is that the create call in FUSE receives the correct uid/gid pair of the NFS client. But subsequent calls which are not bridged by filehandle e.g. unlinkat or utimensat are received as being issued by uid/gid=0, which breaks in my case. 
I didn't read through the ganesha code, but wouldn't it be cleaner, to switch each thread under LINUX using setfsuid/setfsgid for each file handle instead of using setresuid/setresgid only for creations according to the uid/gid used for a filehandle creation and leave ganesha threads with this effective filesystem ID for all FS requests until the thread serves another file handle? Maybe you have a different threading model, but i would imagine that it is implemented with a generic thread pool and then it would not break FUSE underneath. 
There are actually good reasons to use FUSE via the kernel module and not to load directly the application code into an FSAL because the kernel can very effectively cache meta-data and data.

**Comment by ffilz** [comment]
Sorry for not getting back sooner...

We do some operations in FSAL_VFS as root because we have to. Other operations we don't setfsuid/gid because that's an extra step and we don't need the permission checking.

Why does doing operations as root break things?

I get that there may be a caching benefit of using a kernel FUSE mount. All of the in tree library filesystems we use have their own caching and the PROXY FSALs benefit from Ganesha being the NFS client as opposed to a re-export even if they then lose data caching (we do have meta-data caching).

There has been discussion of adding a data caching layer as a stackable FSAL but no one has yet attempted that and the team I'm on doesn't have a solid use case.

**Comment by ffilz** [comment]
Are there still open questions here or can we close this?

**Comment by ralcolea** [comment]
Hi ffilz. I'm interested in developing a custom FSAL for exporting a FUSE file system, like you suggested in your previous comments. 

I looked at FSAL_CEPH and FSAL_GLUSTER examples, and also at the header files fsal.h, fsal_api.h and fsal_types.h, but I'm still a little confused to implement the necessary methods.

I would like to know if you have any examples or documentation more related to FUSE that I can look before continuing?

I want to try to export a simple fuse-based filesystem, with two or three folders and files.

Do you have any advices? 
Thanks in advance. Any help will be appreciated.

**Comment by ffilz** [comment]
So you have a FUSE mounted file system you want to export?

Have you tried using FSAL_VFS?

You could look back in the code history for FSAL_FUSELIKE which was removed in this commit: b67544046e642602ede1dc82328748947a673eca

Unfortunately that was before the new FSAL API, but you could get an idea of what it did.

I have never done any actual work with FUSE stuff and Ganesha, I'm just aware we used to have the FSAL...

**Comment by ralcolea** [comment]
Thank you very much ffilz for your quick reply.

Yes, that's correct. As you say, I have a FUSE mounted file system I want to export using Ganesha.

I haven't tried FSAL_VFS because I wasn't sure if it's gonna work and after reading your suggestions to other user, I though the best option was to develop a custom FSAL for Fuse using the new FSAL API. Anyways, I can also try FSAL_VFS and see how it works.

I will take a look to the previous FSAL_FUSELIKE to get the idea and see how it worked the previous FSAL.

Thank again for your help ffilz. I really appreciate it.

**Comment by ffilz** [comment]
You're welcome. I'll leave this issue open for continued questions as you proceed.

**Comment by ffilz** [comment]
Closing old issues that are not planned for any resolution.

Please re-open with new information if this issue is still of concern.
