### ISSUE TITLE
Why ganesha call unlock when shutdown ? 

### ISSUE THREAD

**Issue by liyinshubyte** [nfs-ganesha/nfs-ganesha#762]
when I shutdown ganesha, I find ganesha will call unlock by the following stack, which maybe caused data corruption.
```
admin_thread->do_shutdown->remove_all_exports->process_unexports->unexport->release_export
->state_release_export->state_export_unlock_all->state_unlock
```

For example, client1 has a byte range lock on ganesha, which lock file1 from byte 100 to byte 200, when I shutdown ganesha, ganesha will unlock the byte range lock. Then restart ganesha, client2 acquire the byte range lock, i.e. lock file1 from byte 100 to byte 200, even though client1 didn't unlock.  This can cause data corruption in the file1, because both client1 and client2 think they has the exclusion lock.

**Comment by dang** [comment]
A clean shutdown cleans up after itself.  If you want to fail over, you should just hard kill ganesha, so it doesn't clean up.  We talked at one point about adding an unclean shutdown, but no one ever did it.

**Comment by ffilz** [comment]
With the in-tree FSALs, there really isn't a way to preserve byte range locks on shutdown without some extra work. There HAS been work done for FSAL_CEPH so the CephFS back end will not release locks if Ganesha crashes (and maybe on intentional shutdown - not absolutely clear what was done there), but it took back end work. For FSAL_VFS and FSAL_GPFS, locks are associated with open file descriptors and therefore when the Ganesha process ends, those file descriptors will be closed by the OS and all locks released. FSAL_GLUSTER and FSAL_CEPH (outside the work discussed above) have client connections that when broken, will release the locks. FSAL_PROXY_V3 is one FSAL where conceivably locks could be sustained over a shutdown if the Ganesha node didn't send an SM_NOTIFY to the server on restart. The NFSv4 protocol, when FSAL_PROXY_V4 restarts would cause dumping of the locks.

From a true HA perspective, FSAL_CEPH is currently the only Ganesha FSAL that offers a mechanism where there is no window where some other process can "steal" the locks before the NFS clients have a chance to reclaim them as part of NFS server crash recovery.

**Comment by liyinshubyte** [comment]
@dang @ffilz Thanks the explanation. Got it.
