### ISSUE TITLE
Question about atime and mtime 

### ISSUE THREAD

**Issue by liyinshubyte** [nfs-ganesha/nfs-ganesha#783]
When I touch f1, then cp f1 f2, and stat f2, I found the access time(Access: 2027-11-25 15:11:38.000000000 +0800) of f2 incorrect.

I find atime comes from high 32 bit of `createhow->createhow4_u.ch_createboth.cva_verf` in `open4_ex_create_args`, and mtime comes from low 32 bit of `createhow->createhow4_u.ch_createboth.cva_verf`. But `createhow->createhow4_u.ch_createboth.cva_verf` also seems incorrect. Not sure what's the reason.

**Comment by ffilz** [comment]
Issue fixed in V4-rc1 between these two patches:

https://github.com/nfs-ganesha/nfs-ganesha/commit/e896e82751f7312b3c8dc768e513dc6d173ca59e
https://github.com/nfs-ganesha/nfs-ganesha/commit/a2a08c2dc6e8fe86058385631c777cd6507ddb2d

With V4.0 tagged, there is currently no intention of back porting any more fixes to V3-stable. Please upgrade to V4.0.

**Comment by liyinshubyte** [comment]
@ffilz 
The patch needs a SETATTR after OPEN, but when I test, there is not a SETATTR after OPEN in NFS4.1. But In NFS4.2 there is a SETATTR after OPEN.

![image](https://user-images.githubusercontent.com/92144382/151100012-cf8c7bf5-8367-424d-b3a2-fc766f86385e.png)

**Comment by ffilz** [comment]
Can you try on Ganesha V4.1? It's possible there's another patch required also but I'm not sure why there would be a difference between NFS v4.1 and v4.2 since this is not in an area where 4.2 changed the spec. The client should be behaving the same way. Are you using the same client for 4.1 and 4.2? If you still see the problem on Ganesha V4.1, please get a tcpdump -s0 -w /tmp/exclusive.tpc trace of the OPEN sequence and I can check to make sure all the bits are set correctly in the OPEN response.

**Comment by liyinshubyte** [comment]
> Can you try on Ganesha V4.1? 

Sure, will test it
