### ISSUE TITLE
Issue with Nested Psudo device 

### ISSUE THREAD

**Issue by skmprabhu1** [nfs-ganesha/nfs-ganesha#811]
Suppose if we add add export1 with Psuedo path /sampleFS/FS1/ and then add export2 with Psuedo path  /sampleFS/FS1/testmnt , then ganesha is throwing invalid error and not starting. 

# systemctl status nfs-ganesha
● nfs-ganesha.service - NFS-Ganesha file server
   Loaded: loaded (/usr/lib/systemd/system/nfs-ganesha.service; disabled; vendor preset: disabled)
  Drop-In: /usr/lib/systemd/system/nfs-ganesha.service.d
           └─10-nofile.conf
   Active: failed (Result: exit-code) since Thu 2022-03-24 09:55:30 EDT; 19s ago
     Docs: http://github.com/nfs-ganesha/nfs-ganesha/wiki
Main PID: 29233 (code=exited, status=2)

Mar 24 09:55:20 c84f2u21-vm6 systemd[1]: Starting NFS-Ganesha file server...
Mar 24 09:55:22 c84f2u21-vm6 systemd[1]: Started NFS-Ganesha file server.
Mar 24 09:55:30 c84f2u21-vm6 systemd[1]: nfs-ganesha.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 24 09:55:30 c84f2u21-vm6 systemd[1]: Unit nfs-ganesha.service entered failed state.
Mar 24 09:55:30 c84f2u21-vm6 systemd[1]: nfs-ganesha.service failed. 

And , corresponding ganesha.log
2022-03-07 11:39:17 : epoch 00210484 : ces02 : gpfs.ganesha.nfsd-249264[dbus] gsh_export_addexport :EXPORT :INFO :Adding export from file: /var/mmfs/ces/nfs-config/gpfs.ganesha.exports.conf with EXPORT(Export_id=885)
2022-03-07 11:39:17 : epoch 00210484 : ces02 : gpfs.ganesha.nfsd-249264[dbus] gpfs_create_export :FSAL :INFO :GPFS get version is 0 options 0x771F1E0 id 885
2022-03-07 11:39:18 : epoch 00210484 : ces02 : gpfs.ganesha.nfsd-249264[dbus] claim_posix_filesystems :FSAL :INFO :Root fs for export /eodc/products/eodc.eu/TEST01 is /eodc/products
2022-03-07 11:39:18 : epoch 00210484 : ces02 : gpfs.ganesha.nfsd-249264[dbus] gpfs_create_export :FSAL :INFO :gpfs_fsal_create: pnfs ds was enabled for [/eodc/products/eodc.eu/TEST01]
2022-03-07 11:39:18 : epoch 00210484 : ces02 : gpfs.ganesha.nfsd-249264[dbus] init_export_root :EXPORT :INFO :Added root obj for path /eodc/products/eodc.eu/TEST01 on export_id=885
2022-03-07 11:39:18 : epoch 00210484 : ces02 : gpfs.ganesha.nfsd-249264[dbus] make_pseudofs_node :EXPORT :CRIT :BUILDING PSEUDOFS: Export_Id 885 Path /eodc/products/eodc.eu/TEST01 Pseudo Path /products/eodc.eu/S1_CSAR_IWGRDH/SIG0/V01R01/EQUI7_AF020M/E039N054T32 LOOKUP E039N054T32 failed with No such file or directory (can't create directory on non-PSEUDO FSAL)
2022-03-07 11:39:18 : epoch 00210484 : ces02 : gpfs.ganesha.nfsd-249264[dbus] mdcache_exp_release :FSAL :INFO :Releasing GPFS export 885 for /eodc/products/eodc.eu/TEST01
2022-03-07 11:39:18 : epoch 00210484 : ces02 : gpfs.ganesha.nfsd-249264[dbus] gsh_export_addexport :EXPORT :CRIT :0 export entries in /var/mmfs/ces/nfs-config/gpfs.ganesha.exports.conf added because (internal error) errors
2022-03-07 11:39:18 : epoch 00210484 : ces02 : gpfs.ganesha.nfsd-249264[dbus] dbus_message_entrypoint :DBUS :MAJ :Method (AddExport) on (org.ganesha.nfsd.exportmgr) failed: name = (org.freedesktop.DBus.Error.InvalidFileContent), message = (0 export entries in /var/mmfs/ces/nfs-config/gpfs.ganesha.exports.conf added because (internal error) errors. Details:
Config File (/var/mmfs/ces/nfs-config/gpfs.ganesha.exports.conf:16712): 1 validation errors in block EXPORT
Config File (/var/mmfs/ces/nfs-config/gpfs.ganesha.exports.conf:16712): Errors found in configuration block EXPORT

In code, gsh_dbus_register_path->gsh_export_addexport->proc_block->add_export_commit->export_commit_common->mount_gsh_export ->pseudo_mount_export->

        /* Now find the export we are mounted on */
        op_ctx->ctx_export = get_gsh_export_by_pseudo(tmp_pseudopath, false); <==== here false means ok for substring search. 

        op_ctx->fsal_export = op_ctx->ctx_export->fsal_export; <=== here we are assigning fsal reference of 1st export, since 1st export comes first and its pseudo path is substring of 2nd export. 
...
....

        /* Get the root inode of the mounted on export */
        fsal_status = nfs_export_get_root_entry(op_ctx->ctx_export, &state.obj); <== Again we are referring 1st export
....
...

Later, 
        /* Now we need to process the rest of the path, creating directories
         * if necessary.
         */
        for (tok = strtok_r(rest, "/", &saveptr);
             tok;
             tok = strtok_r(NULL, "/", &saveptr)) {
                rc = **make_pseudofs_node**(tok, &state);
                if (!rc) {
                        /* Release reference on mount point inode
                         * and the mounted on export
                         */
                        state.obj->obj_ops->put_ref(state.obj);
                        put_gsh_export(op_ctx->ctx_export);
                        return false;
                }
        }

And , in make_pseudofs_node(), the lookup  is failed, failed to create pseudo path, the error is returned to back to gsh_export_addexport().

        /* First, try to lookup the entry */
        fsal_status = fsal_lookup(state->obj, name, &new_node, NULL);
....
...
        if (fsal_status.major != ERR_FSAL_NOENT) {
                /* An error occurred */
                LogCrit(COMPONENT_EXPORT,
                        "BUILDING PSEUDOFS: Export_Id %d Path %s Pseudo Path %s LOOKUP %s failed with %s",
                        state->export->export_id,
                        state->export->fullpath,
                        state->export->pseudopath,
                        name,
                        msg_fsal_err(fsal_status.major));
                return false;
        }

As per the nfs-ganesha documentation from https://github.com/nfs-ganesha/nfs-ganesha/wiki/DBusExports

"Nested exports (where /exp1 and /exp1/some/path/exp2 are both exports) are more properly supported for NFS v4. Nested exports are mostly supported when the two exports use different FSALs. The Pseudo Filesystem may be used to paste various exports together in a flexible manner."

Is this limitation still exists in Ganesha 3.5 version? I would like to more about above limitation. is it possible to have work around and remove limitation?

**Comment by ffilz** [comment]
What version of Ganesha are you using?

Also, are you using dbus to add an export to a running Ganesha, or configuring nested exports in your config file? What FSAL are you using? What is the configuration of the two exports?

**Comment by skmprabhu1** [comment]
Hi Frank,

Ganesha version is 3.5

Also, are you using dbus to add an export to a running Ganesha, or configuring nested exports in your config file? What FSAL are you using? What is the configuration of the two exports?
This is a GPFS environment. we have management command to add new export, the command invoke dbus interface to add new export into ganesha configuration configuration file.


[root@c84f2u21-vm7 ~]# mmnfs export add /ibm/fs2/c --client "*(Access_type=RO,protocols=4,squash=allsquash)" --pseudo /mnt_1/a.c/
mmnfs: The NFS export was created successfully
[root@c84f2u21-vm7 ~]# mmnfs export add /ibm/fs2/c1 --client "*(Access_type=RO,protocols=4,squash=allsquash)" --pseudo /mnt_1/a.c/c1
mmnfs: The NFS export was created successfully
[root@c84f2u21-vm7 ~]# mmnfs export add /ibm/fs2/c2 --client "*(Access_type=RO,protocols=4,squash=allsquash)" --pseudo /mnt_1/a.c/c2
mmnfs: The NFS export was created successfully

EXPORT
{
        Attr_Expiration_Time=60;
        Delegations=none;
        Export_id=11;
        Filesystem_id=666.666;
        MaxOffsetRead=18446744073709551615;
        MaxOffsetWrite=18446744073709551615;
        MaxRead=1048576;
        MaxWrite=1048576;
        Path="/ibm/fs2/c";
        PrefRead=1048576;
        PrefReaddir=1048576;
        PrefWrite=1048576;
        Pseudo="/mnt_1/a.c";
        Tag="/ibm/fs2/c";
        UseCookieVerifier=false;
        FSAL
        {
                Name=gpfs;
        }
        CLIENT
        {
                Access_Type=ro;
                Clients=*;
                Protocols=4;
                Squash=allsquash;
        }
}
EXPORT
{
        Attr_Expiration_Time=60;
        Delegations=none;
        Export_id=12;
        Filesystem_id=666.666;
        MaxOffsetRead=18446744073709551615;
        MaxOffsetWrite=18446744073709551615;
        MaxRead=1048576;
        MaxWrite=1048576;
        Path="/ibm/fs2/c1";
        PrefRead=1048576;
        PrefReaddir=1048576;
        PrefWrite=1048576;
        Pseudo="/mnt_1/a.c/c1";
        Tag="/ibm/fs2/c1";
        UseCookieVerifier=false;
        FSAL
        {
                Name=gpfs;
        }
        CLIENT
        {
                Access_Type=ro;
                Clients=*;
                Protocols=4;
                Squash=allsquash;
        }
}
EXPORT
{
        Attr_Expiration_Time=60;
        Delegations=none;
        Export_id=13;
        Filesystem_id=666.666;
        MaxOffsetRead=18446744073709551615;
        MaxOffsetWrite=18446744073709551615;
        MaxRead=1048576;
        MaxWrite=1048576;
        Path="/ibm/fs2/c2";
        PrefRead=1048576;
        PrefReaddir=1048576;
        PrefWrite=1048576;
        Pseudo="/mnt_1/a.c/c2";
        Tag="/ibm/fs2/c2";
        UseCookieVerifier=false;
        FSAL
        {
                Name=gpfs;
        }
        CLIENT
        {
                Access_Type=ro;
                Clients=*;
                Protocols=4;
                Squash=allsquash;
        }
}

Ganesha service not starting after adding above exports. 
]# systemctl status nfs-ganesha
● nfs-ganesha.service - NFS-Ganesha file server
   Loaded: loaded (/usr/lib/systemd/system/nfs-ganesha.service; disabled; vendor preset: disabled)
  Drop-In: /usr/lib/systemd/system/nfs-ganesha.service.d
           └─10-nofile.conf
   Active: failed (Result: exit-code) since Tue 2022-04-05 10:29:02 EDT; 11s ago
     Docs: http://github.com/nfs-ganesha/nfs-ganesha/wiki
  Process: 31792 ExecStartPost=/bin/bash -c /usr/bin/sleep 2 && /bin/dbus-send --system   --dest=org.ganesha.nfsd --type=method_call /org/ganesha/nfsd/admin  org.ganesha.nfsd.admin.init_fds_limit (code=exited, status=0/SUCCESS)
  Process: 31789 ExecStartPost=/bin/bash -c prlimit --pid $MAINPID --nofile=$NOFILE:$NOFILE (code=exited, status=0/SUCCESS)
  Process: 31785 ExecStart=/bin/bash -c ${ENV_OPTIONS} ${MALLOC_ARENA_MAX} ${NUMACTL} ${NUMAOPTS} /usr/bin/gpfs.ganesha.nfsd -C ${OPTIONS} ${EPOCH} (code=exited, status=0/SUCCESS)
 Main PID: 31786 (code=exited, status=2)

Apr 05 10:28:52 c84f2u21-vm7 systemd[1]: Starting NFS-Ganesha file server...
Apr 05 10:28:54 c84f2u21-vm7 systemd[1]: Started NFS-Ganesha file server.
Apr 05 10:29:02 c84f2u21-vm7 systemd[1]: nfs-ganesha.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 05 10:29:02 c84f2u21-vm7 systemd[1]: Unit nfs-ganesha.service entered failed state.
Apr 05 10:29:02 c84f2u21-vm7 systemd[1]: nfs-ganesha.service failed.

**Comment by ffilz** [comment]
Ah, OK, so you are trying to put c1 and c2 under c in the pseudofs but they are beside c in the GPFS file system?

In order to do this, the directories /ibm/fs2/c/c1 and /ibm/fs2/c/c2 must exist to be used as mount points. Ganesha will ONLY create directories while building the pseudofs for FSAL_PSEUDOFS exports. It doesn't want to mess with real file systems.

I THINK FSAL_GPFS has all the mechanisms to do this, but if there is some issue, try exporting via FSAL_VFS as a cross check.

And give the existence of the mount points, this should work from even earlier than Ganesha V3.5 though it certainly should work in 3.5. What may not work in 3.5 is removing any of those exports.

**Comment by skmprabhu1** [comment]
I have found a issue with the code .


Please find the detailed logs:

   3673 2022-08-17 06:51:05 : epoch 0002007f : c84f2u23-vm7 : gpfs.ganesha.nfsd-15718[main] pseudo_mount_export :EXPORT :DEBUG :BUILDING PSEUDOFS: Export_Id         1 Path /ibm/fs1/export1 Pseudo Path /ibm/fs1/export1 Rest ibm/fs1/export1
   3674 2022-08-17 06:51:05 : epoch 0002007f : c84f2u23-vm7 : gpfs.ganesha.nfsd-15718[main] nfs_export_get_root_entry :RW LOCK :F_DBG :Got read lock on 0xf37        b68 (&export->lock) at /root/rpmbuild/BUILD/nfs-ganesha-2.7.5-ibm067.04.295048/support/exports.c:2177
   3675 2022-08-17 06:51:05 : epoch 0002007f : c84f2u23-vm7 : gpfs.ganesha.nfsd-15718[main] _mdcache_lru_ref :INODE :F_DBG :_mdcache_lru_ref1 obj_handle 0xf3        0818 sub_handle 0xf2d230 refcnt : 3 **===> 0xf2d230 is FSAL PSEUDO object reference**


   3964 2022-08-17 06:51:05 : epoch 0002007f : c84f2u23-vm7 : gpfs.ganesha.nfsd-15718[main] pseudo_mount_export :EXPORT :DEBUG :BUILDING PSEUDOFS: Export_Id         2 Path /ibm/fs1/export2 Pseudo Path /ibm/fs1/export2 Rest ibm/fs1/export2
   3965
   3966
   3967 2022-08-17 06:51:05 : epoch 0002007f : c84f2u23-vm7 : gpfs.ganesha.nfsd-15718[main] nfs_export_get_root_entry :RW LOCK :F_DBG :Got read lock on 0xf37        b68 (&export->lock) at /root/rpmbuild/BUILD/nfs-ganesha-2.7.5-ibm067.04.295048/support/exports.c:2177
   3968 2022-08-17 06:51:05 : epoch 0002007f : c84f2u23-vm7 : gpfs.ganesha.nfsd-15718[main] _mdcache_lru_ref :INODE :F_DBG :_mdcache_lru_ref1 obj_handle 0xf3        0818 sub_handle 0xf2d230 refcnt : 3 **===>  0xf2d230 is FSAL PSEUDO object reference**


   4015 2022-08-17 06:51:05 : epoch 0002007f : c84f2u23-vm7 : gpfs.ganesha.nfsd-15718[main] mdcache_find_keyed_reason :INODE :F_DBG :Looking for hk=eb6883148        12d172d fsal=0x7e4da0 key=0xbf0ae426666358e809002f2f69626d2f66733100000000000000000000000000000000000000000000000000000000000000000000000000000000000        00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
   4016 2022-08-17 06:51:05 : epoch 0002007f : c84f2u23-vm7 : gpfs.ganesha.nfsd-15718[main] cih_latch_entry :RW LOCK :F_DBG :Got read lock on 0xf28378 (&cp->        lock) at /root/rpmbuild/BUILD/nfs-ganesha-2.7.5-ibm067.04.295048/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_hash.h:262
   4017 2022-08-17 06:51:05 : epoch 0002007f : c84f2u23-vm7 : gpfs.ganesha.nfsd-15718[main] cih_get_by_key_latch :HT CACHE :DEBUG :cih AVL hit slot 5602
   4018 2022-08-17 06:51:05 : epoch 0002007f : c84f2u23-vm7 : gpfs.ganesha.nfsd-15718[main] _mdcache_lru_ref :INODE :F_DBG :_mdcache_lru_ref1 obj_handle 0xf2        f118 sub_handle 0xf30c40 refcnt : 2 **===> 0xf30c40 is FSAL GPFS object reference**



   4348 2022-08-17 06:51:05 : epoch 0002007f : c84f2u23-vm7 : gpfs.ganesha.nfsd-15718[main] pseudo_mount_export :EXPORT :DEBUG :BUILDING PSEUDOFS: Looking fo        r export for /mnt_1/abc.de
   4349 2022-08-17 06:51:05 : epoch 0002007f : c84f2u23-vm7 : gpfs.ganesha.nfsd-15718[main] get_gsh_export_by_pseudo :RW LOCK :F_DBG :Got read lock on 0x7ebc        a0 (&export_by_id.lock) at /root/rpmbuild/BUILD/nfs-ganesha-2.7.5-ibm067.04.295048/support/export_mgr.c:598
   4350 2022-08-17 06:51:05 : epoch 0002007f : c84f2u23-vm7 : gpfs.ganesha.nfsd-15718[main] get_gsh_export_by_pseudo_locked :EXPORT :F_DBG :Searching for exp        ort matching pseudo path /mnt_1/abc.de
   4351 2022-08-17 06:51:05 : epoch 0002007f : c84f2u23-vm7 : gpfs.ganesha.nfsd-15718[main] get_gsh_export_by_pseudo_locked :EXPORT :F_DBG :Comparing /mnt_1/        abc.de 13 to /ibm/fs1/export1 16
   4352 2022-08-17 06:51:05 : epoch 0002007f : c84f2u23-vm7 : gpfs.ganesha.nfsd-15718[main] get_gsh_export_by_pseudo_locked :EXPORT :F_DBG :Comparing /mnt_1/        abc.de 13 to /ibm/fs1/export2 16
   4353 2022-08-17 06:51:05 : epoch 0002007f : c84f2u23-vm7 : gpfs.ganesha.nfsd-15718[main] get_gsh_export_by_pseudo_locked :EXPORT :F_DBG :Comparing /mnt_1/        abc.de 13 to /mnt_1/abc.de 13

   4354 2022-08-17 06:51:05 : epoch 0002007f : c84f2u23-vm7 : gpfs.ganesha.nfsd-15718[main] get_gsh_export_by_pseudo_locked :EXPORT :F_DBG :get export ref fo        r id 3 /ibm/fs1/e1, refcount = 3


   4367
   4368 2022-08-17 06:51:05 : epoch 0002007f : c84f2u23-vm7 : gpfs.ganesha.nfsd-15718[main] _mdcache_lru_ref :INODE :F_DBG :_mdcache_lru_ref1 obj_handle 0xf3        12a8 sub_handle 0xf30f70 refcnt : 3   **===> Assigned wrong FSAL object reference. It should be PSEUDO object reference not GPFS object refernece.**
   4369

The problem is that, in get_gsh_export_by_pseudo_locked() , the path is compared with pseudopath and assigned reference of subhandle FSAL (GPFS). This will work if pseudopath and fullpath is same. But it doesn't work if the pseudopath is not same as fullpath of export.


Fix for this issue is compare export->fullpath with path and assign  subhandle FSAL reference. I have tested below fix and it is working fine. 

# git diff
diff --git a/src/support/export_mgr.c b/src/support/export_mgr.c
index 89b3cfc..81b07bc 100644
--- a/src/support/export_mgr.c
+++ b/src/support/export_mgr.c
@@ -563,7 +563,7 @@ struct gsh_export *get_gsh_export_by_pseudo_locked(char *path,

                /* we agree on size, now compare the leading substring
                 */
-               if (strncmp(export->pseudopath, path, len_export)
+               if (strncmp(export->fullpath, path, len_export)
                    == 0) {
                        ret_exp = export;
                        len_ret = len_export;

**Comment by ffilz** [comment]
I don't think that's right. get_gsh_export_by_pseudo_locked is looking for an export by pseudo path.

Who is calling get_gsh_export_by_pseudo_locked? Maybe that's the wrong search to call in this path?

I'll try and set this up with FSAL_VFS and see if I can figure out what's going on.

**Comment by skmprabhu1** [comment]
@ffilz 
Hi Frank,

get_gsh_export_by_pseudo_locked() is called in below sequence. 
pseudo_mount_export->get_gsh_export_by_pseudo->get_gsh_export_by_pseudo_locked


pseudo_mount_export()
{
[...]
[...]
        /* Now find the export we are mounted on */
        op_ctx->ctx_export = get_gsh_export_by_pseudo(tmp_pseudopath, false);

should we call get_gsh_export_by_path() in above?

Thanks,
Prabhu

**Comment by ffilz** [comment]
No it needs to be get_gsh_export_by_pseudo there because we are building the pseudofs.

Hmm, could you also try this one with 4.0 or next?

This is definitely doing something tricky with the pseudofs, it should work, but it IS unusual and requires all the bits and pieces to be correct.

**Comment by ffilz** [comment]
Are you sure you have the directories set up correctly?

I just tested with FSAL_VFS using V3.5 AND next. Here is my directory tree:

```
[root@fedora src]# ls -ld `find /export/test1`
drwxrwxrwx. 5 root root 35 Aug 30 13:36 /export/test1
drwxr-xr-x  4 root root 42 Aug 30 13:37 /export/test1/c
drwxr-xr-x  2 root root 22 Aug 30 13:36 /export/test1/c1
-rw-r--r--  1 root root 17 Aug 30 13:36 /export/test1/c1/desc.txt
drwxr-xr-x  2 root root 22 Aug 30 13:36 /export/test1/c2
-rw-r--r--  1 root root 17 Aug 30 13:36 /export/test1/c2/desc.txt
drwxr-xr-x  2 root root  6 Aug 30 13:37 /export/test1/c/c1
drwxr-xr-x  2 root root  6 Aug 30 13:37 /export/test1/c/c2
-rw-r--r--  1 root root 16 Aug 30 13:36 /export/test1/c/desc.txt

```
Here are my exports:

```
[root@fedora src]# cat /etc/ganesha/nested-test.vfs.conf 
###################################################
#     Export entries
###################################################


EXPORT
{
  Export_Id = 177;
  Path = /export/test1/c;
  Pseudo = /export/c;
  FSAL
  {
    Name=VFS;
  }
  Access_Type=RW;
  SecType = sys;
  CLIENT
  {
  	Access_Type=RW;
  	Squash=None;
  	Clients=simple1*,127.0.0.1,local*,192.168.0.0/24,192.168.1.0/24;
  	SecType = sys;
  }
}

EXPORT
{
  Export_Id = 178;
  Path = /export/test1/c1;
  Pseudo = /export/c/c1;
  FSAL
  {
    Name=VFS;
  }
  Access_Type=RW;
  SecType = sys;
  CLIENT
  {
  	Access_Type=RW;
  	Squash=None;
  	Clients=simple1*,127.0.0.1,local*,192.168.0.0/24,192.168.1.0/24;
  	SecType = sys;
  }
}

EXPORT
{
  Export_Id = 170;
  Path = /export/test1/c2;
  Pseudo = /export/c/c2;
  FSAL
  {
    Name=VFS;
  }
  Access_Type=RW;
  SecType = sys;
  CLIENT
  {
  	Access_Type=RW;
  	Squash=None;
  	Clients=simple1*,127.0.0.1,local*,192.168.0.0/24,192.168.1.0/24;
  	SecType = sys;
  }
}

```
And here is the result of accessing those:

```
[root@fedora src]# mount localhost:/export/c /mnt
[root@fedora src]# find /mnt
/mnt
/mnt/desc.txt
/mnt/c1
/mnt/c1/desc.txt
/mnt/c2
/mnt/c2/desc.txt

```

**Comment by ffilz** [comment]
Maybe enable EXPORT debug at FULL_DEBUG?

**Comment by manishladdha** [comment]
Hi Frank, 
The export command return success for us as well, but when we look at the Ganesha process it crashed.
Could you confirm if Ganesha was OK in  your case ?

**Comment by manishladdha** [comment]
Hi Frank,
I checked the code changes on 3.5, but could not find a link which could have made this case work.
The get_gsh_export_by_pseudo() returns an export* pointing to the FSAL reference always because the new pseudo path will match against the existing psuedo path reference:
(strncmp(export->pseudopath, path, len_export)

This FSAL refernce is being later used 
op_ctx->fsal_export = op_ctx->ctx_export->fsal_export;
and fails because it generates a fsal_name using below code:
fsal_name = op_ctx->ctx_export->fsal_export->exp_ops.get_name(
				op_ctx->ctx_export->fsal_export);
which does not match the requirement: strncmp(fsal_name, "PSEUDO", 6) != 0

Do you see a behavior change with FSAL_VFS w.r.t above observation, please help to check.

**Comment by manishladdha** [comment]
Hi Frank,
Can you please take a look on the above comments and share your inputs.

**Comment by ffilz** [comment]
Do both of the following exist:

/ibm/fs2/c/c1
/ibm/fs2/c/c2

When inserting an NFSv4 export into the pseudofs, Ganesha ONLY creates the necessary directories to reach if IF the pseudofs mount point is in a FSAL_PSEUDO export (where thus the tree is being created in memory). For any other FSAL, Ganesha will NOT create directories.

This may be the root of your problem.

It's also possible there is some quirk of using dbus. If you have all the exports configured in the config file and start Ganesha does it work? If that doesn't work, perhaps enabling EXPORT debug:

LOG {
    COMPONENTS {
        EXPORT = FULL_DEBUG;
   }
}

and examining the log during Ganesha start up would help understand what's going on.

**Comment by manishladdha** [comment]
Hi Frank,
Yes, the directories exist, they were manually created.
Here is my observation:
case1:
add an export for /ibm/fs1/c --pseudo /products/c
and /ibm/fs1/c1  --pseudo /products/c/c1
/ibm/fs1/c2 --pseudo /products/c/c2

The above case works, even if the directories under /products are not created.

case2:
add an export for /ibm/fs1/c --pseudo /ibm/c
and /ibm/fs1/c1  --pseudo /ibm/c/c1
/ibm/fs1/c2 --pseudo /ibm/c/c2

This also works

case3:
add an export for /ibm/fs1/c --pseudo /fs1/c
and /ibm/fs1/c1  --pseudo /fs1/c/c1

the above export failed.

case4:
For example: for an export /abcd/products/abcd.eu/, 

the psuedo path  /products/abcd.eu/P1 doesn't work

but works with change in name: (changed to abcd_eu)
/products/abcd_eu/P1


If the pseudo path is within the filesystem, then Ganesha fails to recognize this and takes reference of the FSAL path as pointed in my previous comments.

**Comment by ffilz** [comment]
Unfortunately I can't test on FSAL_GPFS.

Could you enable FULL_DEBUG for EXPORT and FSAL components and give two logs, one for working case, and one for failing case.  I think that will be enough to make the issue visible.

I'm not quite clear on your case4.

Also could you try just having the exports in the config file at startup rather than using dbus to add them. It's possible something isn't working quite right with dbus add export.

Also, could you try on Ganesha V4.0.11 (next)? Or did you do that already?

**Comment by manishladdha** [comment]
Hi Frank,
Thank you for checking on this.

My earlier tests also had an impact because of root_squash setting on my machine:
Here is the logs with no_root_squash enabled and my observation:

created 2 new exports:
both pseudo directories exist:
mmnfs export add /ibm/fs1/ibm.com/exp21  --client "*(Access_type=RO,protocols=4,squash=allsquash)" --pseudo /mnt_1/abc.de/

mmnfs export add /ibm/fs1/ibm.com/exp22  --client "*(Access_type=RO,protocols=4,squash=allsquash)" --pseudo /mnt_1/abc.de/A

export is successful, client is able to mount the 1st export, but fails for second mount with below error:
mount -o vers=4 10.28.0.236:/mnt_1/abc.de/A /mnt/exp22
mount.nfs: mounting 10.28.0.236:/mnt_1/abc.de/A failed, reason given by server: No such file or directory

After NFS Ganesha restart, the NFS service does not come UP.

The observation is same as pointed in my comment on Sep 30
https://github.com/nfs-ganesha/nfs-ganesha/issues/811#issuecomment-1263494713


Attaching ganesha full debug logs and export.conf:

--> timestamp of restart:
Tue Nov  8 05:34:47 EST 2022
logs indicate: building psuedo tree failed
2022-11-08 05:34:52 : epoch 000100c0 : c84f2u05-vm1 : gpfs.ganesha.nfsd-2865476[main] make_pseudofs_node :EXPORT :CRIT :Manish dumping fsal_name=GPFS/MDC
2022-11-08 05:34:52 : epoch 000100c0 : c84f2u05-vm1 : gpfs.ganesha.nfsd-2865476[main] make_pseudofs_node :EXPORT :CRIT :BUILDING PSEUDOFS: Export_Id 131 Path /ibm/fs1/ibm.com/exp22 Pseudo Path /mnt_1/abc.de/A LOOKUP A failed with No such file or directory (can't create directory on non-PSEUDO FSAL)

[ganesha.log](https://github.com/nfs-ganesha/nfs-ganesha/files/9960302/ganesha.log)
[conf.txt](https://github.com/nfs-ganesha/nfs-ganesha/files/9960313/conf.txt)

**Comment by manishladdha** [comment]
Hi Frank,
Attaching working case logs as well, please note the change in pseudo path name:
mmnfs export add /ibm/fs1/ibm.com/exp21  --client "*(Access_type=RO,protocols=4,squash=allsquash)" --pseudo /mnt_1/abc.de/

mmnfs export add /ibm/fs1/ibm.com/exp22  --client "*(Access_type=RO,protocols=4,squash=allsquash)" --pseudo /mnt_1/abc_de/A

timestamp: Thu Nov 10 00:40:17 EST 2022
[working_conf.txt](https://github.com/nfs-ganesha/nfs-ganesha/files/9977692/working_conf.txt)
[working_case_ganesha.log](https://github.com/nfs-ganesha/nfs-ganesha/files/9977693/working_case_ganesha.log)

**Comment by ffilz** [comment]
I see the functional difference between working and non-working is:

```
conf.txt:                      Pseudo="/mnt_1/abc.de/A";
working_conf.txt:        Pseudo="/mnt_1/abc_de/A";
```

I.e. non-working has an underscore ('_') while working has a period ('.'). The error message for non-working is:

`2022-11-08 05:34:52 : epoch 000100c0 : c84f2u05-vm1 : gpfs.ganesha.nfsd-2865476[main] make_pseudofs_node :EXPORT :CRIT :BUILDING PSEUDOFS: Export_Id 131 Path /ibm/fs1/ibm.com/exp22 Pseudo Path /mnt_1/abc.de/A LOOKUP A failed with No such file or directory (can't create directory on non-PSEUDO FSAL)`

The error is clear. In the working case, A does not exist on the GPFS file system. We ONLY create directories necessary to reach a sub-export when the parent export is FSAL_PSEUDO. On any other FSAL, we expect ALL directories to already exist. This includes the "mount point" of the sub-export.

When exporting such that Pseduo is the same as Path, there is no problem because the directory structure is all there. When Pseudo is not the same as Path, then there is no guarantee the directories are there.

Note that all of this is analogous to mounting local file systems, If you issued:

mount /dev/fs0 /mnt/abc
mount /dev/fs1 /mnt/abc/A

We would expect the file system on /dev/fs0 mounted as /mnt/abc to have a sub-directory "A" in it's root directory such that the path "/mnt/abc/A" is valid after mounting /dev/fs0, This provides the mount point for /dev/fs1, This is no different that the requirement that the path /mnt/abc exist in the root file system before mounting /dev/fs0.

**Comment by skmprabhu** [comment]
below config will recreate the issue:
Export1 : /mnt/exp1 => pseudo path = /mnt/pseudo1
Export2 : /mnt/exp2 => pseudo path = /mnt/exp1/

**Comment by ffilz** [comment]
Manish,

So non-working is:

`        Export_id=130;
        Path="/ibm/fs1/ibm.com/exp21";
        Pseudo="/mnt_1/abc.de";
        Export_id=131;
        Path="/ibm/fs1/ibm.com/exp22";
        Pseudo="/mnt_1/abc.de/A";
`

And working is:

`        Export_id=132;
        Path="/ibm/fs1/ibm.com/exp21";
        Pseudo="/mnt_1/abc.de";
        Export_id=133;
        Path="/ibm/fs1/ibm.com/exp22";
        Pseudo="/mnt_1/abc_de/A";
`

Note that in the non-working example, export_id 133 will be sub-mounted under export_id 132.

In order to do this, /ibm/fs1/ibm.com/exp21/A must be a valid path in the local file system.

In the working case, export_id 133 is sub-mounted under export_id 0, the pseudofs implemented with FSAL_PSEUDO. In that case, /mnt_1 has already been created, and adding export_id 133 will create /mnt_1/abc_de and then /mnt_1/abc_de/A.

In the non-working case, it finds /mnt_1/abc.de is export_id 133, which maps to the local file system directory "/ibm/fs1/ibm.com/exp21. It then does a lookup for A (in export_id 132) and doesn't find it. Since exort_id 132 is GPFS, Ganesha is not allowed to create A.

If you think A exists, I guess the next step would be to create on small enough EXT4 file systems that you can create them inside files that can then be shared along with a config that I can then set them up in my system.

**Comment by ffilz** [comment]
I should add that while what you are trying to do IS supported by Ganesha, assuming all the required directories exist, it is best when using FSAL_VFS or FSAL_GPFS exports for Path and Pseudo to be the same for each export, I,e, if you have a sub-export, it is exporting a file system that is sub-mounted on the file system exported by the parent export.

When you do otherwise, confusion is introduced because Ganesha requires empty directories to exist in the actual file system in order for Ganesha to have a place to attach the sub-export to. Ganesha ONLY allows itself to create directories in FSAL_PSEUDO exports because that is a RAM only solution, and the handles are constructed using the path name so the handles are persistent.

**Comment by manishladdha** [comment]
Hi Frank,
This worked after I created directory 'A' under /ibm/fs1/ibm.com/exp21. I always created it under the pseudo path which is not at all required.
Now I understand how Ganesha picks the export id 0 for the above working case, behaving as expected.

Thank you for the analysis and detailed explanation.

**Comment by ffilz** [comment]
You're welcome and sorry that this was confusing what was necessary. Can we close this now?

**Comment by manishladdha** [comment]
Yes please, thanks again.
