### ISSUE TITLE
question: why are you trying to refresh attrs of src file in cache_inode_rename?

### ISSUE THREAD

**Issue by akiradeveloper** [nfs-ganesha/nfs-ganesha#86]
``` c
        status_ref_dir_src = cache_inode_refresh_attrs_locked(dir_src);

        if (dir_src != dir_dest)
                status_ref_dir_dst =
                        cache_inode_refresh_attrs_locked(dir_dest);

        status_ref_src = cache_inode_refresh_attrs_locked(lookup_src);

        LogFullDebug(COMPONENT_CACHE_INODE, "done refreshing attributes");

        if (FSAL_IS_ERROR(fsal_status)) {
                status = cache_inode_error_convert(fsal_status);

                LogFullDebug(COMPONENT_CACHE_INODE,
                             "FSAL rename failed with %s",
                             cache_inode_err_str(status));

                goto out;
        }

        if (lookup_dst) {
                /* Force a refresh of the overwritten inode */
                status_ref_dst = cache_inode_refresh_attrs_locked(lookup_dst);
                if (status_ref_dst == CACHE_INODE_ESTALE)
                        status_ref_dst = CACHE_INODE_SUCCESS;
        }
```

I am seeing this code and understood you are trying to update the attrs of cache inodes after fsal rename. But how are you sure that calling getattrs on the previous (must be deprecated) file succeeds?

In particular, I think this line always fails because the src is nowhere in the fsal backend.

``` c
status_ref_src = cache_inode_refresh_attrs_locked(lookup_src);
```

Or the anticipation on the fsal rename method is that it keeps the old entry?

**Comment by akiradeveloper** [comment]
My guess is that refreshing the cache node attr by lookup_src returning ESTALE error should be benign. Ganesha's code now assumes that src entry is still available after fsal rename.

**Comment by ffilz** [comment]
Returning ESTALE will not be benign if the inode has state associated with it since that will cause the inode to be dumped along with all it’s state.

It could also bubble back to the client which would cause the client to decide the inode was gone.

Also, a rename doesn't make a new inode and should not change the handle.

We may see an ESTALE on the lookup_dst if the rename causes removal of that file (but it might also still exist if there were other hard links to that inode).

**Comment by akiradeveloper** [comment]
@ffilz 
Thanks for response but I was asking about `lookup_src`, not dst.

I should explain in more detail. see the comments in the code.

especially in case of renaming symlink, there is no guarantee that getattrs on the old symlink is successful.

```c
        // calling FSAL rename op makes new (dest) name on the backend
        // and may have deprecated the old (src) name.
        fsal_status =
            dir_src->obj_handle->obj_ops.rename(lookup_src->obj_handle,
                                                dir_src->obj_handle, oldname,
                                                dir_dest->obj_handle, newname);
        

        LogFullDebug(COMPONENT_CACHE_INODE, "returned from FSAL rename");

        // this is ok
        status_ref_dir_src = cache_inode_refresh_attrs_locked(dir_src);

        // this is also ok
        if (dir_src != dir_dest)
                status_ref_dir_dst =
                        cache_inode_refresh_attrs_locked(dir_dest);

        // why do we need to refresh the old attr? (this calls FSAL getattrs)
        // it may be gone and getattrs call may not be successful.
        status_ref_src = cache_inode_refresh_attrs_locked(lookup_src);
```

**Comment by ffilz** [comment]
Hmm, I would have to dig deeper as to exactly why we need to update attr on renamed entry.

Obviously if srcdir/src and destdir/dest were the same inode, the refreshing of the attr of lookup_dest would catch the reduced link count for the inode.

I would suggest asking a question in the nfs-ganesha mailing list where all developers will see rather than issue tracker where just a few developers will see.

**Comment by ffilz** [comment]
Also, do we have to actually worry about renaming a symlink? I don't think a *ix client could ever issue a RENAME operation for a symlink. Also, not all FSALs are limited in ability to query the attributes of a symlink.

**Comment by akiradeveloper** [comment]
> Also, do we have to actually worry about renaming a symlink? I don't think a *ix client could ever issue a RENAME operation for a symlink.

Really?

nfstest_posix has test of renaming symlink. I am wondering if other targets pass this test..

**Comment by akiradeveloper** [comment]
Wow!!

Looking into the mailing list and I found the line in discussion is introduced by you in May 2015!

https://review.gerrithub.io/#/c/228379/

**Comment by akiradeveloper** [comment]
@ffilz 

```c
        /* Update the attributes for the removed entry */
        (void)cache_inode_refresh_attrs_locked(to_remove_entry);

        status = status_ref_entry;
        if (status != CACHE_INODE_SUCCESS) {
                LogDebug(COMPONENT_CACHE_INODE,
                         "cache_inode_refresh_attrs_locked(entry %p %s) returned %s",
                         entry, name, cache_inode_err_str(status_ref_entry));
        }
```

This is a part of the code from `cache_inode_unlink`. Conceptually, rename and remove is similar because rename is considered as operation that creates the new object and then remove the old one.

What we see is that unlink also queries the attributes of old entry (probably due to the same reason of your patch) *but* discards the result while your patch in `cache_inode_rename` uses the result.

For `cache_inode_rename`, I suppose reading the attributes of old entry is necessary but should discard the result.

**Comment by ffilz** [comment]
Will need to look again, but I think this came about because the pjdfstests POSIX tests found we were not reflecting updated ctime on the renamed inode.

Also: "Conceptually, rename and remove is similar because rename is considered as operation that creates the new object and then remove the old one."

Not exactly... Conceptually it is an atomic LINK of the new name and UNLINK of the old name. The object continues to be the same object (and thus it's handle SHOULD NOT change - though I understand in some cases handle can change, not sure clients are really prepared to handle that case though).

**Comment by ffilz** [comment]
Can this issue be closed? I will close it next week if there is no response otherwise.
