### ISSUE TITLE
Readdir slow with NFS + Gluster

### ISSUE THREAD

**Issue by dspisla** [nfs-ganesha/nfs-ganesha#869]
Our customer suffers from bad performance when doing a DIR listing on folders with a lot of subfolders . See here some of this results

> Path        | Folders count | First access | Second access
> /path1/... | 630                 | 0m9.884s     | 0m0.007s
> /path2/... | 764                 | 1m3.123s     | 0m0.155s
> /path3/... | 878                 | 1m6.645s     | 0m0.006s

He tries to access the same folder from the two servers, which mount this NFS volume, and he can confirm that only the first access is slow (in details, he try to list a folder content from the first server and it is slow, he then immediately list the content of the same folder from the second server and it is quick).

It looks to us something related to how the access is cached, not in the instructions he use to mount the volume, but just for completeness, he is mounting the volume using this instruction:

 10.100.xx.xxx:/my_volume /my_volume/data nfs   rw,hard,lock,async,intr,nodev,nfsvers=3  0 0

Our server side configuration is as follows:
nfs-ganesha-3.5-11.1.x86_64
glusterfs-8.5

Share config:

> 
> EXPORT {
> 	Export_Id = 3;
> 	Protocols = 3, 4;
> 	path = "/my_volume";
> 	Pseudo = "/my_volume";
> 	Access_Type = None;
> 	Squash = no_root_squash;
> 	Sectype = sys;
> 
> 	FSAL {
> 		Name = "GLUSTER";
> 		Hostname = "localhost";
> 		Volume = "my_volume";
> 		volpath = "/my_volume/data";
> 	}
> }

**Is there any chance to improve the DIR listing behavior by adjusting the Share config?**
I just noticed that a similar issue was open some days ago:
https://github.com/nfs-ganesha/nfs-ganesha/issues/868

But in the backend Ceph is beeing used, not Gluster

**Comment by dang** [comment]
Can you be a bit more specific?  By "server" here, do you mean multiple Ganesha NFS servers?   Or do you mean multiple NFS clients?

If it's multiple Ganesha servers, then the problem must be with Gluster, since the two Ganeshas cannot talk to each other at all.  A slow first readdir on one Ganesha followed by a fast readdir on  a second Ganesha means that some cache in Gluster is being filled by the first access.

If it's multiple clients, then probably something it wrong with readdir on Gluster, and the Ganesha dirent cache is working correctly to make subsequent accesses fast.  Typically, in the past, this means that readdir_plus was not compiled into Ganesha.  This means that the version of Gluster that Ganesha was built against didn't have the glfs_xreaddirplus_r() function in libgfapi.

**Comment by dspisla** [comment]
Hello dang,
Its a multiple Ganesha servers (4 nodes at all). The customer is accessing from 2 client nodes via CTDB Cluster IP i.e. he is accessing the same Ganesha node since the Cluster Ip is referencing one node.

We also assume that Gluster readdir ist not working properly. I am in contact with a Gluster Specialist and discussing this issue with him. We are using Ganesha community packages for SLES 15, I don't have any information if this Ganesha version was built against a Gluster version that includes glfs_xreaddirplus_r() function in libgfapi.

@dang Do you know if ganesha uses a readdir or readdir*p* to perform a DIR listing?

**Comment by dang** [comment]
If, at the time Ganesha was built, the gluster libraries included glfs_xreaddirplus_r(), then we will use that.  Otherwise, we will fall back on glfs_readdir_r(), which is much slower for Ganesha's usage.  There is no runtime checking, it's all done at build time, so you will have to contact your packager to see which way it's built.

**Comment by dspisla** [comment]
@dang  Ok, thanks so far. I will try out to get some information about the package building process.

I will also close the issue for now. There are no more questions from my side so far.
