### ISSUE TITLE
How to unmarshal/marshal ganesha config file with other language ? 

### ISSUE THREAD

**Issue by chenxinlong** [nfs-ganesha/nfs-ganesha#908]
I've noticed that nfs-ganesha write a config parser itself , it there a way to manipulate this kind config content by using other language(like Golang) ?

**Comment by dang** [comment]
Do you mean making changes to the config parser?  I think the answer in general is no.   Ganesha is written in C, and only C code is used within it (with a few exceptions, like using gtest, which is written in C++).  We don't have provisions for using other languages for internal Ganesha code.

There is helper code written in python, however, that make use of the DBus APIs that Ganesha makes available.  Since it's DBus, you can use any language you want to interface with that, as long as it has DBus bindings.   Some configuration can be done via DBus, but no all of it.

**Comment by chenxinlong** [comment]
Thanks.
