### ISSUE TITLE
Q: why didn't fsal_open2 tuncate file if file is exists and create mode is UNCHECKED

### ISSUE THREAD

**Issue by wf-caravaggio** [nfs-ganesha/nfs-ganesha#942]
hi,all:
I've been reading the ganesha code and RFC 8881 recently.
RFC 8881 below:
UNCHECKED4 means that the file should be created if a file of that name does not exist and encountering an existing regular file of that name is not an error. For this type of create, createattrs specifies the initial set of attributes for the file. The set of attributes may include any writable attribute valid for regular files. When an UNCHECKED4 create encounters an existing file, the attributes specified by createattrs are not used, except that when createattrs specifies the size attribute with a size of zero, **the existing file is truncated**.

open4ex code below:
```
/* FSAL_UNCHECKED, may be a truncate
* and we need to pass in the case
* of fsal_reopen2 case.
*/
if (FSAL_TEST_MASK(sattr.valid_mask,
		   ATTR_SIZE) &&
   sattr.filesize == 0) {
	LogFullDebug(COMPONENT_STATE,
		     "Truncate");

```
but,  the fsal_reopn2 is invoked ony if file_state isn't null
```
/* Check if there is already a state for this entry and owner.
 */
*file_state = nfs4_State_Get_Obj(file_obj, owner);
if (*file_state == NULL) {
.....
fsal_open2()
.....
}else if (createmode >= FSAL_EXCLUSIVE) {
.....
**fsal_reopen2()**
.....
}else {
}
```
Doesn't fsal_open2 need to truncate files? for example, multi clients open same file.

**Comment by ffilz** [comment]
Multiple clients wouldn't implicate this situation since nfs4_State_Get_Obj is looking for a state with the same owner, so must be the same open owner on the same client. So this is the same open owner (presumably the same process) opening the file a second time with O_TRUNCATE. Could you verify this with a tcpdump trace (and also possibly verify the application is expecting this behavior).

In any case, I need to think about this situation but I think you're right, fsal_reopen2 may need to do a truncate in this case.

**Comment by wf-caravaggio** [comment]
The nfs4_State_Get_Obj function tries to find the state based on the owner. If there(cache) is no owner, there is no state. It does not reject the open request.
I'm thinking about a sequence of events like this
```
ClientA    |   ClientB     |  Server
lookup     |               |  file not found
           |   lookup      |  file not found
open       |               |  create file
           |   open        |  file found, state and owner not found
```
Since linux does not use share_deny, ClientB Send open with Unchecked will open and truncate file.

**Comment by ffilz** [comment]
Right, and that case should not call reopen2 since clientB does not have an existing open owner and state for the file, it will call open2 instead which should handle the truncate.

Note also that since there is no synchronization between the processes and exclusive create is not used, the state of the file really is pretty undefined.

Now the case where we might not truncate as expected would be a single process doing:

open(O_CREAT)
write some data
open(O_CREAT | | O_TRUNC)

Now the 2nd open WILL find the existing open owner and state and call reopen2, but no truncate will occur.

**Comment by ffilz** [comment]
Oh, wait, you were asking about truncate for fsal_open2, that should happen, if the open is an OPEN4_CREATE, UNCHECKED4 and the size attribute is set to 0, openflags will have FSAL_O_TRUNC added. Those openflags get passed to fsal_open2 and fsal_reopen2 in all cases.

If you are seeing an actual case where a truncate isn't happening when expected, I will need a tcpdump -s0 -w to get a binary trace file and some debug logging. STATE=FULL_DEBUG and FSAL=FULL_DEBUG so I can see why it didn't do a truncate.

**Comment by wf-caravaggio** [comment]
Yes, you're right. fsal_open2 does perform truncate file, which is in compliance with the protocol's requirements. There is no issue with this.

**Comment by ffilz** [comment]
OK, so is there any issue left to be resolved?

**Comment by wf-caravaggio** [comment]
I don't have any more questions. It was a very pleasant conversation.
Thanks.
