### ISSUE TITLE
Packages missing for v4.5 on SLES15SP4

### ISSUE THREAD

**Issue by rafikc30** [nfs-ganesha/nfs-ganesha#954]
Currently, we are using Ganesha v3.5 in conjunction with gluster8, and we are interested in upgrading to v4.5 with gluster11. However, it appears that the repository https://download.opensuse.org/repositories/home:/nfs-ganesha:/SLES15SP4-nfs-ganesha-4/15.4/x86_64/ does not have the necessary packages for v4.5. Only versions up to v4.4 are available.

One alternative could be to update to v4.4 instead of 4.5. Before proceeding, we would like to seek your input. Is there any particular reason why v4.5 is not included in the repository? Would you recommend updating from v3.5 to v4.4, or do you have any suggestions for other versions we should consider?

**Comment by ffilz** [comment]
At this point you should consider updating to V5.2 or later. V5.x includes a major improvement in the LRU.

We don't actually have a V4.5 tag... There are a couple patches in V4.4.1 but we never tagged V4.5...

**Comment by rafikc30** [comment]
@ffilz , I appreciate the information you shared. I recall observing v4.5 mentioned in the releases, although I may have misremembered.

Regarding v5.2, it appears that it has not been made available yet. Could you provide an estimated timeframe for the release of v5.2? Additionally, considering our utilization of a production system, Given that the releases have barely been tested in production, do you believe it would pose a significant risk to promptly deploy version 5.2 into production?

**Comment by ffilz** [comment]
What distribution do you need V5.2 for? It's available for Fedora and Centos.

I'm not sure that 4.x has had that much more production use, though it has had at least some.

Unfortunately Ganesha has not had enterprise level testing of the latest version for the past several releases and even the CI is currently broken.

**Comment by rafikc30** [comment]
@ffilz we are using SLES15SP4.

**Comment by kalebskeithley** [comment]
packages for 4.5 don't exist because, as ffilz said, no such release or tag exists. (Not even on Fedora or CentOS ;-))

While we had decided that ganesha4 was EOL, we have revisited the decision and will likely add some fixes to ganesha4 and be tagging a version 4.5 in the coming weeks. Once we do, packages will get built in OBS for SLES as soon as someone (likely me) has a chance to build them. (Note that building packages is not my $dayjob so it might take a few days after tagging before they get built.)

In the mean time, 4.4 is certainly a viable option. I don't suggest 5.1 or 5.2 for you only because I haven't built SLES packages in OBS yet.

**Comment by rafikc30** [comment]
@kalebskeithley Thank you for your response. I will now update to v4.4. Perhaps, when the v5.X version becomes accessible for SLES15, I could consider updating it, given that it encompasses significant enhancements to the LRU. However, I would like to know if you have any concerns or opinions that argue against this.

**Comment by ffilz** [comment]
Closing as we no longer support V4.x, V5.7 has been out for some time now.
