### ISSUE TITLE
RFE:  add compatibility option for running in LXC unpriv. container

### ISSUE THREAD

**Issue by devZer0** [nfs-ganesha/nfs-ganesha#965]
i was surprised that nfs-ganesha (told to be "pure userspace nfs") has issues running inside unprivileged container ( https://discuss.linuxcontainers.org/t/nfs-ganesha-in-lxc/2401 )  because of vfs_open_by_handle and open_by_handle_at

would it be possible to add some compatibility option so we are able to use nfs-ganesha inside lxc without security relaxation/seccomp tuning/quirks ?

**Comment by dang** [comment]
Unfortunately, no.  The semantics of the NFS protocol require that we be able to open by handle, and the linux kernel devs have decided that those APIs need a CAP to use.   We could do things that would sort-of work some of the time (like try to keep a massive database of every handle we've ever given out to (one of) it's path(s)) but these workarounds would be extremely fragile, and time and space consuming, and wouldn't work in all the cases anyway.  This is, unfortunately, one of the many ways that the NFS semantics are incompatible with the POSIX semantics.

**Comment by devZer0** [comment]
sad to hear :(

i have feared that, but thank you for the valuable feedback/insight why it's impossible/difficult.

**Comment by ffilz** [comment]
It's more possible that an unprivileged container could be used for a back end that is accessed by a user space library, but even then we run into issues with little bits and bobs requiring privilege for the container. DBUS is one sticking point I can think of.

But yes, FSAL_VFS can not run without privilege.

What would be nice is for it to be easier to fine tune the CAPs a container has available. The CAP_DAC_SEARCH (I think that's the right one) for open_by_handle is a pretty constrained CAP.

**Comment by ChrysoliteAzalea** [comment]
@devZer0 @ffilz 

> What would be nice is for it to be easier to fine tune the CAPs a container has available. The CAP_DAC_SEARCH (I think that's the right one) for open_by_handle is a pretty constrained CAP.

Well, you can fine-tune them, for privileged containers, however, ```open_by_handle_at``` isn't very safe to use in a privileged container. For example, what happens if a user sends us a file handle that points to a file outside of the directory that is bind mounted to the container?

> Unfortunately, no. The semantics of the NFS protocol require that we be able to open by handle, and the linux kernel devs have decided that those APIs need a CAP to use. We could do things that would sort-of work some of the time (like try to keep a massive database of every handle we've ever given out to (one of) it's path(s)) but these workarounds would be extremely fragile, and time and space consuming, and wouldn't work in all the cases anyway. This is, unfortunately, one of the many ways that the NFS semantics are incompatible with the POSIX semantics.

As an alternative, we can add an option to try to identify files by hard-linking them into a special directory. For example, when a client asks us for a handle pointing to a specific file, the server can hard-link that file into a "work" directory and represent the handle in its name. When a client asks a server to perform an operation on a file with a specific handle, it's accessed through the hard link.

**Comment by ffilz** [comment]
Access outside the export by handle spoofing is always a risk... Solution has always been to have dedicated filesystems for export. Ganesha doesn't give NFS clients access to arbitrary filesystems (and though I haven't coded it YET, Ganesha could restrict access to a filesystem to clients using an export that does export at least part of that filesystem).

The hard link idea could sort of work, but there would still be some issues:

- If a process other than the NFS server does an unlink, the handle link prevents the file from actually being deleted
- A persistent file handle still has to be created so any lookup of the file produces the same handle, and that has to be no matter which name for the file is used
- NFS unlink is by directory handle and name, not handle of object being unlinked
- And OOPS - the big killer - directory handles... you can't hard link directories...

The hard link solves a bit of the database problem, but ultimately is just a database.

**Comment by ChrysoliteAzalea** [comment]
Not related to NFS, but I've found something weird about file handles in Linux -- I've been experimenting with file handles, and found out that anonymous files created with ```memfd_create``` system call also have file handles that can be retrieved with ```name_to_handle_at``` with ```AT_EMPTY_PATH``` flag. Then, any privileged process that knows its file handle can open it with ```open_by_handle_at``` (in this case, ```mount_fd``` can be any file descriptor created with ```memfd_create```). Which seems very strange to me (like, OverlayFS doesn't support file handles, but memfd does?).

**Comment by ChrysoliteAzalea** [comment]
> And OOPS - the big killer - directory handles... you can't hard link directories...

We can hard-link files and sym-link directories (the problem that renaming a directory would break the links, so renaming a directory would be effective "mkdir+rmdir").

One of the problems I've had with it is that some filesystems (like OverlayFS, which is widely used in Docker) don't support handles (I think it's weird why anonymous files that only exist in RAM do have file handles and an actual filesystem like OverlayFS doesn't), and I'm thinking of work-arounds (however, some filesystems don't support hard-links either). Currently the solution I've settled with is bind-mounting the directory I need to export so nfs-ganesha accesses the actual underlying filesystem instead of OverlayFS (although it means I can't write changes since it's a SquashFS partition), and mounting OverlayFS over NFS on the client side (and syncing the upper layer later).

**Comment by ffilz** [comment]
Can we close this?

**Comment by ffilz** [comment]
Closing, no response in more than 60 days.
