### ISSUE TITLE
Why does not  ganesha  itself check permission of directory for OP_OPEN, OP_CREATE?

### ISSUE THREAD

**Issue by zhitaoli-6** [nfs-ganesha/nfs-ganesha#996]
For operations of regular file like OP_READ and OP_WRITE,  ganesha check the permission by "fsal_obj_ops->test_access". 

However, **for those operations(like OP_OPEN, OP_CREATE, OP_LINK, etc) that need write permission of  directory, ganesha itself does not check the permission by `test_access` .  It seems that Ganesha expects FSAL will do the permission check internally for fsal_obj_ops like `open2`, `mkdir`, etc.** 

I am quite confusd  about where  permission check should be dealt with, Ganesha or internal FSAL? Could anyone help me?

**Comment by zhitaoli-6** [comment]
I have seen some comments `The FSAL layer MAY have added an inherited ACL` in fsal_api.h for obj_ops like `mkdir`, `mknode`, `symlink`, `open2` and `setattr2`, which may denote that permission check shall be done in FSAL.

Could anyone explain more about "the FSAL layer MAY have added an inherited ACL", so that permission check should be dealt with in FSAL?

**Comment by ffilz** [comment]
I'm not actually sure about the inherited ACL issue, but the big issue with Ganesha doing directory permission checking is that it can't do it atomically with the operation. This is particularly an issue with rename, where rename over an existing file unlinks the existing file. If there was a race, Ganesha could determine the new file name doesn't exist, so only does permission checking for writing to the directory. Meanwhile another process creates a file with the new name. The Ganesha rename would then unlink that new file even if the user didn't actually have permission to do that.

By deferring the permission checking to the back end file system, the back end file system then IS able to do the permission checking and operation atomically.

ACLs could also be a factor given that multiple ACLs can impact a directory operation which again makes it difficult to do things atomically.

**Comment by zhitaoli-6** [comment]
Thank you for your reply!

>  but the big issue with Ganesha doing directory permission checking is that it can't do it atomically with the operation.

I think it is not an issue if directory permission check is not atomic. Users of file system may accept that for concurrent inflight requests A and B,  both `A -> B` and `B -> A` are ok.  Users expect linearizability: if A is issued after B, then A can see the update of B.
 
In above rename example, it is ok to delete a new file as long as the user have the directory `Write` permission. 

I'm still confused why for some operations, permission is checked by ganesha calling obj_ops->test_access(), while for some other operations,  permission is not checked by ganesha.

**Comment by zhitaoli-6** [comment]
Is it ok for me to add related permission check by calling obj_ops->test_access() in directory OPs?

**Comment by ffilz** [comment]
Where do you want to add the call and which ops?

What is the need for Ganesha to do this permission checking?

**Comment by ffilz** [comment]
Is this still an issue?

**Comment by zhitaoli-6** [comment]
Sorry for this late reply. 

I still think that the usage of `fsal_obj_ops->test_access` is not clear in nfs-ganesha. Now this function is called in following cases:
<img width="646" alt="image" src="https://github.com/nfs-ganesha/nfs-ganesha/assets/13163985/beced69f-5d45-4051-b06b-6ea910c316be">


If non-atomicity results in directory permission not handled by nfs-ganesha, then it is also non-atomic for regular file operations like read/write. There maybe another process who change permission while nfs-ganesha use stale permission.

**Comment by ffilz** [comment]
It is true that non-atomicity could impact an I/O operation, however, the worst that happens is the race window between the I/O and the permission change is widened a tiny bit (very little for FSALs that can do invalidate upcalls since that immediately makes the old permissions invalid). Note also that in POSIX, once you have a file open, you continue to have access despite permission changes, so revoking permission has no guarantee of immediately cutting off access to a file (granting permission just results in a delay before the newly permitted user actually gaining access). So the negative impact of the race is close to nil. Note also that the ONLY way to have NFSv3 I/Os "atomically" permission check would be to open/read or write/close for EVERY operation. That would result in terrible performance.

The difference with directory operations is that the race due to non-atomic permission checking can actually expose something that could never happen if all activity was via local filesystem operations. There are applications that use rename to serialize operations that depends on the atomicity of rename. By deferring to the backend for directory operations, we preserve the ability to do that serialization.

So we have struck a balance that allows for correctness of directory operations and maintains a reasonable performance for I/O.

**Comment by zhitaoli-6** [comment]
Thanks for your patient explanation. It is more clear for me. Directory operations are about metadata, which is more important in permission checking.
